- phpunit/phpunit/4.7/phpunit.xml.dist
The base supported version is ~4.7~ 6.1 as specified in the ~directory~ version aliases
> Fix PHPUnit xsd version

- javiereguiluz/easyadmin-bundle/master/etc/routing/easy_admin.yaml
I think it's a better idea to expose the controller itself directly.
It would encourage people to add their own controller by just changing the name of the bundle if they want to override it.
Also, I would suggest to change `master` for a lower requirement (1.14 or 1.15 maybe, there are some without much BC breaks, and they'd still share the same recipe) and add `version_aliases`, but haven't done it in the PR because `master` might have been added for a specific reason 🙂
> Recommend specifying the controller itself for EasyAdmin

- symfony/framework-bundle/3.3/etc/packages/app.yaml
[As caught by @xabbuh](https://github.com/symfony/symfony-standard/pull/1064#discussion_r114080504), in the docs, voters are stored in `Security`, not in `Voter`.
> Store voters in Security

- lexik/jwt-authentication-bundle/2.3/Makefile
- lexik/jwt-authentication-bundle/2.3/etc/packages/lexik_jwt_authentication.yaml
- lexik/jwt-authentication-bundle/2.3/manifest.json
- lexik/jwt-authentication-bundle/2.3/post-install.txt
Alternative to https://github.com/symfony/recipes-contrib/pull/5, I think it would be more appropriated here as this bundle has no competitor regarding the need it solves. 
Repository: https://github.com/lexik/LexikJWTAuthenticationBundle
> Add LexikJWTAuthenticationBundle

- symfony/framework-bundle/3.3/etc/packages/app.yaml
Related to https://github.com/symfony/recipes/pull/42 and https://github.com/symfony/symfony-standard/pull/1064
> Add comments

- symfony/framework-bundle/3.3/etc/packages/framework.yaml
As deprecated and "removed" in https://github.com/symfony/symfony/pull/21830 and https://github.com/symfony/symfony/pull/22238 (BC break)
> Remove framework.trusted_proxies option

- symfony/framework-bundle/3.3/src/Kernel.php
`import()` is an implementation detail; see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Loader/GlobFileLoader.php#L26
Fixed ticket: https://github.com/symfony/symfony/pull/22638
> Load container config, instead of importing it

- lexik/jwt-authentication-bundle/2.3/manifest.json
> [LexikJWTAuthenticationBundle] Add aliases

- symfony/framework-bundle/3.3/Makefile
Related to #49, I don't know if this the best way to do it. But as the Makefile is composed I don't think it's possible to use advanced Makefile features 😟
@greg0ire suggested something like this: 
```makefile
.PHONY: serve
CONSOLE=bin/console
$(CONSOLE):
@echo 'Woops! The console does not exist'
@exit
serve: bin/console
bin/console list server|grep server:start
bin/console server:start
```
But don't know if you can have multiple targets with the same name but different conditions?
> [FrameworkBundle] improve Makefile serve target

- symfony/framework-bundle/3.3/Makefile
In case that the server could not start we should indicate the failure
with a non-zero exit code.
This addresses @stof's comment in https://github.com/symfony/recipes/pull/54#discussion_r116276643.
> fix error exit code

- symfony/framework-bundle/3.3/etc/packages/app.yaml
> Tweak configuration for app.yaml

- README.rst
- phpunit/phpunit/4.7/manifest.json
`version_aliases` was a bad idea as it incurs too much manual maintenance as we need to remember to add new minor and major versions. That's fragile and we will probably forget to do it promptly. That's even worse for contributed recipes.
So, instead (and as already documented in the README, so not part of the diff), the version of the recipe if the minimum version that the recipe supports. So, if there is only one recipe for version "3.3", the recipe will be applied for all versions >= 3.3 (including 3.x, 4.x, ...).
If a version introduces changes that has an impact on the recipe , then a new directory with the version when the break appeared should be created with the new recipe, which makes total sense.
> Remove version_aliases configuration setting

- doctrine/doctrine-bundle/1.6/manifest.json
When requiring `doctrine/doctrine-bundle` (more often `orm-pack`), the following is added to the project `.env`:
```
DATABASE_URL=mysql://root@127.0.0.1:3306/symfony?charset=utf8mb4&serverVersion=5.7
```
The makefile seems to parse that properly (tested on OSX and debian).
But running `source .env` from the cli (for debugging the .env vars, as shown in [dotenv docs](http://symfony.com/doc/master/components/dotenv.html)) gives
> .env:15: parse error near `&'
This fixes it by adding quotes around the value.
> [doctrine/doctrine-bundle] Escape DATABASE_URL env value

- lexik/jwt-authentication-bundle/2.3/etc/packages/lexik_jwt_authentication.yaml
- lexik/jwt-authentication-bundle/2.3/manifest.json
Only using `%ETC_DIR%` leads to
> Private key "etc/jwt/private.pem" does not exist or is not readable.
This fixes it by prefixing paths by `%kernel.project_dir%/` in the bundle config.
> [lexik/jwt-authentication-bundle] Fix configured key path

- lexik/jwt-authentication-bundle/2.3/Makefile
| Q | A |
| --- | --- |
| License | MIT |
The definition of the `generate-jwt-keys` target broke the `Makefile` when the `openssl` binary is not available.
> [lexik/jwt-authentication-bundle] Fix generate-jwt-keys target in Makefile

- doctrine/doctrine-bundle/1.6/etc/packages/prod/doctrine.yaml
It's time to move forward.
`doctrine/cache` since [1.6.0](https://github.com/doctrine/cache/releases/tag/v1.6.0) (see doctrine/cache#115):
* `ApcuCache` added
* `ApcCache` deprecated
`doctrine/doctrine-cache-bundle` since [1.3.0](https://github.com/doctrine/DoctrineCacheBundle/releases/tag/1.3.0) (see doctrine/DoctrineCacheBundle#86):
* `apcu` added in the configuration
> [doctrine/doctrine-bundle] Use apcu provider instead of deprecated apc

- symfony/framework-bundle/3.3/etc/packages/app.yaml
Even if the best practice is to store tests under `tests/`, some might still want to store them under `src/Tests` in which case, we want to exclude them for several reasons: first, no service should be defined there, so no need to scan the directory. But, more important, if PHPUnit is only install as a dev dependency, scanning on production will fail as the PHPUnit classes won't be available. This PR fixes this.
> Exclude Tests from being scanned

- behat/symfony2-extension/2.1/behat.yml.dist
- behat/symfony2-extension/2.1/features/bootstrap/FeatureContext.php
- behat/symfony2-extension/2.1/features/bootstrap/bootstrap.php
- behat/symfony2-extension/2.1/features/demo.feature
- behat/symfony2-extension/2.1/manifest.json
- behat/symfony2-extension/2.1/post-install.txt
As Behat is part of the official Symfony documentation, I'm creating this PR in here. This recipe will create files already configured for Symfony 4 and will create a demo working scenario showing how to get access to Symfony's kernel and send a request to it.
> Add the Behat recipe

- symfony/framework-bundle/3.3/web/index.php
This PR removes the check blocking access to debug features if `APP_DEBUG` is set and the IP is not a local one because:
* unlike with the old system of front controllers (`app.php` and `app_dev.php`), it's very unlikely that someone will set `APP_DEBUG` to true in production and if the variable isn't set, debug features aren't enabled
* it makes Flex painful to use (by default) in virtualized environments (example with Docker: https://github.com/dunglas/symfony-docker-skeleton/pull/3#issuecomment-310892861)
* the spirit of Flex is to be minimalist by default, this kind of check should be added by the user if he wants it, not removed if he doesn't need it
The goal of this PR is mainly to open the discussion about this.
> [framework-bundle] Remove the IP check in web/index.php

- sensiolabs/security-checker/4.0/manifest.json
The auto-scripts entry now relies on the fact that Composer adds the bin-dir in the PATH instead of asking the Flex plugin to run a php-script.
Fixes https://github.com/symfony/flex/issues/109
> Support alternative bin dirs for the security checker

- symfony/framework-bundle/3.3/Makefile
When renaming the directory structure, this was forgotten.
> Fix `make serve` with web-server-bundle

- symfony/twig-bundle/3.3/config/routing/dev/twig.yaml
This prefix has always been `/_error`, in singular (see https://github.com/symfony/symfony-standard/blob/3.3/app/config/routing_dev.yml#L11).
In addition to avoiding a BC break, I think `/_error/404,500,...` reads better than `/_errors/404,500,...`
> Fix the prefix of the Twig dev routes

- README.rst
- symfony/framework-bundle/3.3/src/Kernel.php
With the changes in #123, we would have the three main way of configuring Symfony using the same naming convention: `services.yaml`, `routes.yaml`, and `bundles.php`.
> Rename container.yaml to services.yaml

- symfony/framework-bundle/3.3/Makefile
This has been fixed in Symfony directly now.
> Remove unneeded flag

- api-platform/core/2.1/config/packages/api_platform.yaml
We recently changed the way to configure resources' paths in API Platform 2.1.0 beta 3, see https://github.com/api-platform/core/pull/1271.
> [API Platform] Update the API Platform config to use the new mapping paths

- symfony/framework-bundle/3.3/config/services.yaml
> (2/2) FileLoaderLoadException
> The file "../../src" does not exist (in: /tmp/sf/config) in /tmp/sf/config/services.yaml (which is loaded in resource "/tmp/sf/config/services.yaml").
> [framework-bundle] fix resources path

- symfony/framework-bundle/3.3/public/index.php
Let's sort the `use` statements because, otherwise, the default front controller triggers an error when using PHP CS Fixer:
> Fixed CS of the default front controller

- symfony/swiftmailer-bundle/2.5/config/packages/dev/swiftmailer.yaml
Proposed changes:
* Disable by default the sending of emails (as we currently do in Symfony 3.x: https://github.com/symfony/symfony-standard/blob/3.3/app/config/config_test.yml)
* Use `delivery_addresses` instead of `delivery_address`
* Added minimal help notes and a link to Symfony Docs
> Update the SwiftMailer recipe for dev environment

- symfony/framework-bundle/3.3/src/Kernel.php
Remove the `final` keyword for the `Kernel` class. First, I don't think this is needed, but more important, that's why `cache:clear` with warmup does not work with Flex.
> Remove final from Kernel

- behat/symfony2-extension/2.1/features/bootstrap/bootstrap.php
- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
As described in https://github.com/laravel/framework/issues/7354 and linked issues, getenv() is not thread safe - this can lead to issue with concurrent requests, on Windows especially.
> Dont use getenv(), use $_SERVER instead

- symfony/swiftmailer-bundle/2.5/config/packages/dev/swiftmailer.yaml
- symfony/swiftmailer-bundle/2.5/manifest.json
The current configuration for the mailer is done in 2 different places:
* `.env` configures the mailer to use localhost as a transport;
* but the `dev` environment disables delivery.
That's very confusing. As `.env` is for dev, I propose to use a `null` transport by default (which disables delivery) and remove `disable_delivery` in the `dev` configuration. That makes the configuration centralized in one file instead of two (and yes, I had a WTF moment with this :)).
I'm not sure about the test environment as we don't have a good story about test env + env vars for now, so I haven't changed it for now.
> Change the default mailer configuration

- symfony/framework-bundle/3.3/public/index.php
> Default to non-debug in index.php

- doctrine/doctrine-migrations-bundle/1.2/config/packages/doctrine_migrations.yaml
- symfony/framework-bundle/3.3/config/services.yaml
Alternative to #87
Migration classes are very different from "regular" classes. They should not be autoloaded (and they cannot be autoloaded anyway if you are using `organize_migrations: BY_YEAR` as the namespace generated by Doctrine does not take into account sub-directories).
So, to sump up, even if Doctrine migration classes look like regular classes, they are not.
That said, I propose to make some tweaks to the current configuration to have a better default:
* I think renaming `Migrations/` to `Migration/` should not be done (see #87) as having `Migrations` is a signal that this directory is not like the other ones.
* Excluding `Migrations/` from container auto-configuration is required to avoid errors (classes do not …
> Fix Doctrine migrations default configuration

- sensio/framework-extra-bundle/4.0/config/packages/framework_extra.yaml
- sensio/framework-extra-bundle/4.0/manifest.json
As of 3.3, Symfony automatically registers the annotations when installed.
> Remove unneeded configuration

- symfony/framework-bundle/3.3/src/Kernel.php
I ran into issues trying to create parameters based on `%env()%` during compile-time. This made sense and was expected once I thought about it more.
In discussion with @nicolas-grekas, the solution I was looking for was being able to set parameters directly based on environment. However, `parameters.ini` is no longer a thing going forward.
Since there was no easy or obvious way to do this, we discussed adding `/conf/services_{envs}.yaml` as optional files that can be read to configure the container's services and parameters based on the appropriate environment.
This should allow me to configure `/conf/services_dev.yaml` to be specific to my local develompent environment without having any impact on anyone else running my …
> Make it possible create environment-specific services and parameters.

- symfony/framework-bundle/3.3/src/Kernel.php
See reasoning in https://github.com/symfony/flex/pull/162.
Does the recipes CI check that PHP files are syntactically valid btw?
> Allow PHP 7.0

- symfony/framework-bundle/3.3/src/Kernel.php
There is no other 7.1 specific code in this repo, and there is none at all in recipes-contrib.
> Fix PHP 7.0

- symfony/security-bundle/3.3/config/packages/security.yaml
- symfony/security-bundle/3.3/config/packages/test/security.yaml
This reverts #131. See: https://github.com/symfony/recipes/pull/131#issuecomment-333964855
And while I think this should be reverted, I'd still like to brainstorm ways to make testing with authentication easier :).
> Removing security test config (reverts 131)

- symfony/framework-bundle/3.3/config/packages/framework.yaml
In 2015, we changed from the native PHP session handler to the file based one, which stores in `var/session`. Here is the history: https://github.com/symfony/symfony-standard/pull/904
In that PR, we (imo) narrowly decided to do that (versus keeping with the native session handler), and one big reason was because the SE had a `var/session` dir (the argument being... if we have that dir, shouldn't we use it?). @xabbuh also had one argument about conflicting sessions with multiple PHP apps on one machine (https://github.com/symfony/symfony-standard/pull/904#issuecomment-163192748). Is that actually a real issue?
There are 2 big advantages to using the native PHP session handler:
* This is one less directory that you need to …
> Use the native PHP session handler by default

- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
In debug mode, cache files need to be writeable by everyone for a good dev experience. In `prod`, they do not (and the way the cache system is built these days makes this very easy - yay!).
This change is consistent with how `index.php` already exists: enable `umask` for debug, but not otherwise. This gives great DX for dev, and forces users to setup permissions properly for prod.
I've also proposed removing the warning about permissions... basically because if this is for debug mode only, is there really an issue with `umask(0000)`? There are many things in debug mode you would not want to do/expose in prod mode (e.g. web debug toolbar). This is just another one of those.
P.S. I wasn't sure why there is a …
> Always using umask(0000) in debug mode

- doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml
by leveraging Symfony's cache pools, we can provide a default cache configuration for Doctrine.
Using "cache.system" for metadata and query caches will make them cleareable with a simple "cache:clear", even when APCu is used as a backend - and will auto-select the best available backend, usually APCu, or OPcache.
The result cache is not a system cache, so it should not be cleared on cache:clear, and should be shared when eg a Redis cache is configured for cache.app.
ping @weaverryan as you were interested into this.
> [DoctrineBundle] Enable caches by default on prod

- symfony/twig-bundle/3.3/manifest.json
`templating` being also `symfony/templating`, when using `composer req templating`, it's ambiguous. Right now, the alias takes precedence, which means that you get an error like "Templating component is not installed" and it's kind of difficult to debug. So, let's remove the alias.
> Remove templating as an alias

- friendsofphp/php-cs-fixer/2.2/.php_cs.dist
- friendsofphp/php-cs-fixer/2.2/manifest.json
I let myself add proposal for main repo, as PHP CS Fixer came from Sensio Labs.
If you disagree, simple close this PR :+1:
I added recipe for PHP CS Fixer 2.2, as it's oldest supported version. Recipe is valid for any `^2.2`
> Add PHP CS Fixer recipe

- symfony/framework-bundle/3.3/src/Kernel.php
To preserve BC, autowiring still wires things in hybrid 2.8/3.3 modes.
But 2.8 mode is really a foot gun.
I propose to add a new parameter in SF3.4, to opt-out of this 2.8 mode, and enable this strict mode for all new projects.
WDYT?
> Enable container.autowiring.strict_mode

- symfony/framework-bundle/3.3/config/packages/test/framework.yaml
Session system is not enabled by default in prod & dev. see https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/packages/framework.yaml#L8
So it should also not be enabled by default in test env.
> Do not enable session in test env by default

- symfony/framework-bundle/3.3/src/Kernel.php
Hello,
This PR fix an issue when creating a new `symfony/skeleton` project.
`Fatal error: Declaration of App\Kerne_::getCacheDir() must be compatible with App\Kernel::getCacheDir(): string`
The exception appear when configuring `symfony/framework-bundle`
Hope it's helpful.
> FrameworkBundle kernel should be compatible

- symfony/framework-bundle/3.3/config/services.yaml
See https://github.com/doctrine/DoctrineBundle/pull/727
But also, this directory was always safe to auto-register. If they cannot be autowired, unless you try to *use* them as services, they will be discarded without showing the autowiring failure.
> Remove "Repository" directory from being ignored in service auto-registration

- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
So that setting "`-e prod`" or `APP_ENV=prod` is enough to turn `APP_DEBUG` to false.
> Make "APP_DEBUG" mode fallback to "APP_ENV !== prod"

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
Not ready to merge yet, because this relies on DI >=3.4.
If we want to allow this with 3.3, we might patch DoctrineBundle.
But before doing so, what about just moving to require >=3.4 for all Symfony components?
Any other idea?
> [DoctrineBundle] resolve parameters inside DATABASE_URL

- symfony/framework-bundle/3.3/src/Kernel.php
Replace `dirname(__DIR__)` in App\Kernel with `$this->getProjectDir()`
> Use $this->getProjectDir() instead of dirname(__DIR__)

- symfony/framework-bundle/3.3/src/Kernel.php
Sibling to https://github.com/symfony/symfony/pull/24872
> Enable container.dumper.inline_class_loader param by default

- symfony/workflow/3.3/config/packages/workflow.yaml
- symfony/workflow/3.3/manifest.json
Just a proposal. Reasons:
* it would allow to better separate the app config;
* it improves discoverability (you no longer would have to guess that workflows were configured in config/packages/framework.yaml);
* it aligns with Flex philosophy (small and stand alone config files instead of just 1 big config file).
> [RFC] Added a recipe for the Workflow component

- api-platform/core/2.1/config/routes/api_platform.yaml
If not, it overrides the / namespace, which is not so nice.
> Change the default route to API platform to /api

- symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml
Unless someone has a compelling argument against this, I think it makes sense to be opinionated and not log 404 errors in production by default.
> Ignoring 404 errors in the production logs by default

- doctrine/annotations/1.0/config/routes/annotations.yaml
- doctrine/annotations/1.0/manifest.json
- symfony/routing/3.3/config/routes.yaml
Let's make routes configuration when using annotations automatic.
> Move routes config for annotations

- symfony/framework-bundle/3.3/config/services.yaml
This was proposed in #250 and #251 but closed without merging. But it looks like a needed change. In the Symfony Demo we also exclude this dir to avoid errors. See https://github.com/symfony/demo/blob/e186324d39c43bd0d251ab5c201a4444f3c84f3a/config/services.yaml#L31
> Exclude DataFixtures/ from the autowired services

- symfony/translation/3.3/config/packages/translation.yaml
- symfony/translation/3.3/manifest.json
I propose to revert the changes done in #249. These are my reasons for doing so ... but of course there could be strong reasons too to not do it.
-----
We've been using `translations/` for months ... and two days ago it was suddenly changed to `config/translations/`. There wasn't a public discussion about it. Not even a single comment in #249. The proposal was made at 18:12 CET and merged at 18:50 CET. Just 38 minutes!!
-----
The full dir structure of a modern Symfony project is:
```
assets/
bin/
config/
public/
src/
templates/
tests/
translations/
var/
vendor/
```
Removing `translations/` won't make it significantly more compact. However, hiding it inside `config/` has a serious drawback: instead of being self-explanatory …
> [RFC] Revert the move of translations/ into config/

- php-http/httplug-bundle/1.6/config/packages/httplug.yaml
- php-http/httplug-bundle/1.6/manifest.json
- php-http/httplug-pack/1.0/manifest.json
I know this repo should be for packages endorsed by  "Symfony Core Team". There are a few Symfony core team developers active in HTTPlug and I really think this package should be in the "official" recipe repository. 
The HTTPlug bundle and client abstraction should be the default/recommended way to send HTTP request in a Symfony application. This pack includes Guzzles PSR7 implementation and the lightweight [curl client](https://github.com/php-http/curl-client) from php-http. 
FYI, early next year we will have a PSR for HTTP client that are compatible with HTTPlug. 
See docs: http://docs.php-http.org/en/latest/index.html
See bundle docs: http://docs.php-http.org/en/latest/integrations/symfony-bundle.html
------------
I added …
> Adding HTTPlug pack

- README.rst
The example `manifest.json` from `symfony/framwork-bundle` is a little outdated, uses `make` etc..
> Update full manifest.json example

- behat/symfony2-extension/2.1/features/bootstrap/bootstrap.php
- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
`composer install --no-dev` fails when Dotenv is a dev dependency (which
it is in skeleton) and you're running in an environment without an
APP_ENV variable set (say you're testing prod-like settings locally).
After that `bin/console help` also fails, as does
`bin/console --env=prod help` (as Dotenv is loaded before the argument
can be read).
`APP_ENV=prod bin/console help` works but instead lets avoid needing to
remember that by only trying to load Dotenv if it actually exists.
Strictly speaking this is only required for console, however I have
placed the check in the other places Dotenv is included for consistency.
See https://github.com/symfony/skeleton/issues/32 for some initial pondering relating to this.
> Add checks for Dotenv before calling it

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/1.6/manifest.json
- doctrine/doctrine-bundle/1.6/post-install.txt
In order to run `cache:warmup`, you need to set the server platform and server version. I believe this can be accomplished by using some fake string like `DATABASE_URL: 'mysql://?server_version=5.7`
In this PR, I attempt to make the `DATABASE_URL` *truly* optional during `cache:warmup`. I do this by committing the server (e.g. mysql) and version (e.g. 5.7) into a config file. This allows us to create a fallback when needed.
On the downside, `doctrine.yaml` looks a little strange. Also, I suppose it might be less obvious if you forget to specify `DATABASE_URL` on production (because your connection will fail vs a `Missing DATABASE_URL environment variable` error).
On the upside, you can once again run `cache:warmup` with no …
> Always set Doctrine server version & platform

- symfony/framework-bundle/3.3/config/packages/framework.yaml
Hey guys!
Today, I saw someone accidentally enable sessions with this config:
```yml
framework:
session: ~
```
This mean that their app tried to store sessions in `var/`, and things got weird (especially because it was on Vagrant). This change is to make it as obvious as possible that you should uncomment all *three* lines to get the recommended behavior.
Cheers!
> Making it more clear how to enable sessions

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
With annotations, the code seems to work with or without the trailing `\`. But if you change this to `type: xml`, then you *must* remove the trailing `\`.
So, let's remove it - it makes changing to XML easier... if you're into that sorta thing.
Thanks!
> Removing \ which does not work for XML

- phpunit/phpunit/4.7/manifest.json
- phpunit/phpunit/4.7/phpunit.xml.dist
- phpunit/phpunit/4.7/post-install.txt
- symfony/phpunit-bridge/3.3/bin/phpunit
- symfony/phpunit-bridge/3.3/manifest.json
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
- symfony/phpunit-bridge/3.3/post-install.txt
Several changes to have a better phpunit integration:
- ~~move `phpunit.xml.dist` to framework bundle so that a global phpunit works, and env vars are correctly added to it from the beginning~~
- add `SymfonyTestsListener` to `phpunit.xml.dist` so that using phpunit directly still enables the bridge (if the bridge is not installed, phpunit just ignores the listener)
- recommend installing `simple-phpunit` when `phpunit/phpunit` is installed
- add `bin/phpunit` helper script to run phpunit when simple-phpunit is installed (borrowed from [our own in symfony/symfony](https://github.com/symfony/symfony/blob/master/phpunit))
> Prefer simple-phpunit over direct phpunit deps

- symfony/framework-bundle/3.3/post-install.txt
In this setup docs, we're already using the `composer require server` alias. Why not also use it here?
> Using the alias

- doctrine/doctrine-fixtures-bundle/3.0/manifest.json
We released DoctrineFixturesBundle 3.0 yesterday. In it, we actually recommend putting fixtures classes in the more "shallow" `DataFixtures` directory. The `ORM` is not needed anymore, because fixtures are tagged services - they can really live anywhere.
There is a 2.4 recipe in `recipes-contrib`. But I thought 3.0 could be official.
There are no documentation changes needed. We don't doc usage of this bundle on `symfony-docs` currently, and the docs in the bundle are already updated.
> adding DoctrineFixturesBundle 3.0 recipe

- README.rst
- symfony/framework-bundle/3.3/manifest.json
After #239, we don't need APP_DEBUG anymore, and it can be confusing in fact (when mixing a `.env` setting with `-e prod`)
> Remove defaults for APP_DEBUG env vars

- symfony/framework-bundle/3.3/config/packages/framework.yaml
- symfony/framework-bundle/3.3/manifest.json
- symfony/framework-bundle/3.3/public/index.php
Add two convenient environment variables to set trusted proxies and hosts: `APP_TRUSTED_PROXIES` and `APP_TRUSTED_HOSTS`.
This very convenient when deploying a Symfony app to a cloud platform using load balancers (exemple: Google Container Engine) and/or when using Docker for local development (ex: HTTP/2 reverse proxy, Varnish...). For an example of real world usage see api-platform/api-platform#422.
Backported from api-platform/api-platform#422
> [FrameworkBundle] Add a env vars to configure trusted proxies and hosts

- phpunit/phpunit/4.7/post-install.txt
- symfony/phpunit-bridge/3.3/bin/phpunit
- symfony/phpunit-bridge/3.3/post-install.txt
phpunit 6.5 is the last to support 7.0, so this is the last bump.
when installing phpunit/phpunit:
when installing the bridge:
> Bump phpunit to 6.5, discourage phpunit/phpunit more

- .editorconfig
In PhpStorm, the default indentation for JSON files is 2 spaces, which may be why most new PR start by getting a validation error complaining about indentation.
Many IDEs (including PhpStorm) support EditorConfig today. This file will ensure that any contributor using such an IDE will get the right JSON indentation from the start in the IDE.
> Add the EditorConfig file to enforce JSON indentation

- symfony/translation/3.3/manifest.json
My first Flex experience: How to get the `translations` folder?
`composer require translations => supported aliases: "translation", "translator"`
This adds a `translations` alias for the translator recipe. Maybe its helpful
> add translations alias for translator recipe

- phpunit/phpunit/4.7/phpunit.xml.dist
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
If we don't do that, phpunit is not able to compute the code coverage.
We get the following error without it:
```
Error:         Incorrect whitelist config, no code coverage will be generated.
```
> Fixed default phpunit.xml.dist: add filter/whitelist

- symfony/framework-bundle/3.3/config/packages/test/framework.yaml
Hi guys!
Honestly, the session is a bit of a usability issue - see #262. This at least clarifies what's going on in this file - e.g. "Do I need to uncomment this? Or is the default value ok for my tests?". This was added in #223 so the test environment was consistent with the other environments (no session by default). That was the correct decisions... but this session stuff is annoying (you need to remember to uncomment it in 2 places now).
> Clarify when you would uncomment the session config

- symfony/phpunit-bridge/3.3/config/services_test.yaml
- symfony/phpunit-bridge/3.3/manifest.json
Soon, we will document that you should create public aliases if you need to access a private service from a test. What do you guys think about giving them this configuration file? Creating it in the FWBundle recipe seemed overkill. But if you install phpunit, it seems much more likely that it will be needed.
> Adding services_test.yaml when you install phpunit

- symfony/routing/3.3/config/routes.yaml
- symfony/routing/4.0/config/packages/dev/routing.yaml
- symfony/routing/4.0/config/packages/routing.yaml
- symfony/routing/4.0/config/routes.yaml
- symfony/routing/4.0/manifest.json
Since in Symfony 4  we encourage to use `controller` keyword in prefix, an example configuration should also use this keyword instead of `defaults`.
> [Routing] Use "controller" keyword in example config

- symfony/debug-bundle/3.3/manifest.json
- symfony/debug-pack/1.0/manifest.json
Right now, the `debug` alias installs the debug bundle. I think it's better to actually link this alias to the debug pack. I thought this was the case, but apparently, that's an oversight. Should fix many issue people have right now.
> Move the debug alias to the pack instead of the bundle

- phpunit/phpunit/4.7/post-install.txt
I found the current wording confusing as to why phpunit/phpunit was being discouraged. Was there a bug in it? A security flaw? Is the recipe bad? After speaking with the community, it turns out it was merely because Symfony's bridge is more useful to the user than vanilla phpunit. I feel this new message is more useful to developers.
> Updating notice wording

- symfony/framework-bundle/3.3/public/index.php
Previously the null coalescing logic was duplicated, this puts it into
one place.
Variable names match those used in [bin/console](https://github.com/symfony/recipes/blob/fc9b47d94185fa51a1c7c1ddf3f91b7c4ff5bc93/symfony/console/3.3/bin/console#L26-L27)
> Work out values for env and debug once

- symfony/monolog-bundle/3.1/config/packages/test/monolog.yaml
> Added monolog in test env

- symfony/framework-bundle/3.3/config/packages/framework.yaml
- symfony/framework-bundle/3.3/config/packages/test/framework.yaml
Enabling session by default has only one practical downside: some classes/services are loaded but never used. Not a big deal.
STILL, this is something that is going to be fixed on Symfony by https://github.com/symfony/symfony/pull/25699, where the session is made extra-lazy.
Thus, this is my proposal to fix #262.
> [symfony/framework-bundle] Enable session support by default

- phpunit/phpunit/4.7/post-install.txt
Composer just gives a 'phpunit/phpunit could not be found in require but it is present in require-dev' notice without the `--dev` switch.
(Assumes PHPUnit isn't being used in production of course. 😉)
> Fix composer remove phpunit/phpunit command

- symfony/framework-bundle/3.3/post-install.txt
Current advice results with adding `"symfony/web-server-bundle"` into `require` section in composer.json.
We should advice `composer require server --dev` in order to add 
`"symfony/web-server-bundle"` into `require-dev` section in composer.json
> Add `--dev` to composer require server suggestion

- symfony/framework-bundle/3.3/post-install.txt
It looks like only passing the document root when starting PHP's internal web server behaves slightly different compared to the process that is bootstrapped when using the WebServerBundle (see symfony/symfony#25911). This changes the command suggestion to be (almost) the same of what is done when using the `server:start` command.
> tweak internal web server arguments

- symfony/framework-bundle/3.3/src/Kernel.php
By using `is_dir()` directly, we prevent correct resource tracking.
Let's delegate that to glob-tracking resources.
The brackets are required to tell our glob-resources where the static prefix stops (making the part after it optional - ie the folders/files don't have to exist.)
> [framework-bundle] Let glob figure out existing dirs and fix resource tracking

- doctrine/doctrine-bundle/1.6/manifest.json
This reverts sha:ba7fcf10ccb0cc84f16e029dc0bf6a6509680f3b - #361.
That originally was meant to solve: https://github.com/symfony/symfony/issues/26056
The problem is that the change breaks the database in `phpunit.xml.dist`. It ends up like this:
```
<env name="DATABASE_URL" value="'mysql://root:@127.0.0.1:3306/test_maker'"/>
```
And so, because the string starts with a `'`, it seems to parse this as the database name - I get>
> Unknown database 'mysql://root:@127.0.0.1:3306/test_maker''
> Revert quotes: breaks database in phpunit.xml.dist

- symfony/security-bundle/3.3/config/packages/security.yaml
Hi guys!
A friend of mine made a mistake in his `access_control` because he didn't realize that only the *first* access control that matches is used. I thought the best way to make this easier would be to add a few examples and some very small docs.
I've checked that leaving `access_control` empty like this is "ok" - the configuration system just treats it like an empty array.
> Adding access_control examples and small warning

- symfony/framework-bundle/3.3/post-install.txt
See: https://github.com/symfony/recipes/pull/353#discussion_r165009263
I thought we could just change it to `php -S 127.0.0.1:8000 -t public index.php`. But when I do this, it ALWAYS loads `index.php` - it *never* loads an asset. I don't think we can pass a router argument at all, unless it's smart enough (like `router.php` is in WebServerBundle) to serve the static file if it exists:
https://github.com/symfony/symfony/blob/f74bda51ebd5c66c20dac455d119f407901ad364/src/Symfony/Bundle/WebServerBundle/Resources/router.php#L30
Of course this reverts a fix for this bug: https://github.com/symfony/symfony/issues/25911
I just don't think the built-in web server can work in all cases without our custom router. We can only make it …
> Re-adding doc root to the web server command

- doctrine/doctrine-bundle/1.6/post-install.txt
If you use `symfony/website-skeleton`, you get this craziness :)
We just need to be careful that each post-install (other than FWBundle) has some context about it, so we don't have 3 "Next:" headers. I added the DoctrineBundle message, so shame on me :).
Cheers!
> Tweaking doctrine post message to look good in context of others

- symfony/console/3.3/bin/console
- look for the `--env` and `--no-debug` only before a `--` separator, to respect the support for `--`
- avoid passing an empty string as parameter option name (which would never match anyway, but causes php warning is some Symfony versions instead of being ignored silently, because of https://github.com/symfony/symfony/issues/26136).
> Improve the console script

- symfony/phpunit-bridge/3.3/manifest.json
It feels natural to type `composer require tests` just like we do with `composer require templates`.
> Add "test" and "tests" aliases for the phpunit bridge

- easycorp/easyadmin-bundle/1.17/config/packages/easy_admin.yaml
- easycorp/easyadmin-bundle/1.17/config/routes/easy_admin.yaml
- easycorp/easyadmin-bundle/1.17/manifest.json
We've moved the Composer package from `javiereguiluz/easyadmin-bundle` to `easycorp/easyadmin-bundle` ... so I guess we need to update the recipes too. I don't know if I must also delete the entire `javiereguiluz/` directory.
> Moved the EasyAdmin recipe to its new vendor

- friendsofphp/php-cs-fixer/2.2/manifest.json
There's no specific reason to ignore those files in subdirectories IMO.
> [friendsofphp/php-cs-fixer] Ignore files in root directory only

- symfony/framework-bundle/3.3/src/Kernel.php
This is an annoying detail :). If you change the `bundles.php` file by hand (e.g. to add a bundle manually - not common, but I just did it for some internal bundles), the container will not rebuild. I tested this this fixes that issue.
> Add container tracking to bundles.php so the container rebuilds when it changes

- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
When you specify APP_DEBUG in the ENV, it is interpreted as a "_string_" which triggers this kind of error:
```
Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\HttpKernel\Kernel::__construct() must be of the type boolean, 
string given, called in /app/public/index.php on line 49 and defined in /app/vendor/symfony/http-kernel/Kernel.php:76
Stack trace: 
#0 /app/public/index.php(49): Symfony\Component\HttpKernel\Kernel->__construct('prod', '0') 
#1 {main} thrown in /app/vendor/symfony/http-kernel/Kernel.php on line 76
```
This PR aims to solve that issue.
> unless I missed a trick
> Fix TypeError argument when APP_DEBUG is set

- symfony/framework-bundle/3.3/src/Kernel.php
https://github.com/symfony/recipes/pull/379 introduced a major bug (making all commands/controllers unusable) by not importing this FQCN. As a result, fresh installations get this error:
> Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FileResource" from namespace "App".
Reported by `@AO` on Symfony Slack. Thanks!
> Fixed not imported FQCN in Framework recipe

- symfony/debug-bundle/4.1/config/packages/dev/debug.yaml
- symfony/debug-bundle/4.1/manifest.json
See https://github.com/symfony/symfony/pull/23831 regarding the feature.
Always enabling it on dev mode should be safe, as the server dumper fallbacks on the original dumper if the server isn't listening. So everything should work as usual.
> [DebugBundle] Enable the VarDumper server dumper by default on dev

- symfony/webpack-encore-pack/1.0/manifest.json
By default, it is a good idea to add the npm/Yarn error logs to .gitignore when installing the Encore package so they don't accidentally get committed. There are many common situations which cause an error log to be generated, whether through running commands, or installing Node.js packages. In my case, it was because the Encore command exits with a code of 1 when `yarn run encore --help` is run.
> Add npm and Yarn error logs to .gitignore

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
Simple: Symfony 3.3 is no longer supported. So, no need for this message anymore.
> removing the Symfony 3.3 warning, because that version is no longer supported

- symfony/phpunit-bridge/4.1/bin/phpunit
- symfony/phpunit-bridge/4.1/manifest.json
- symfony/phpunit-bridge/4.1/phpunit.xml.dist
- symfony/phpunit-bridge/4.1/post-install.txt
- symfony/test-pack/1.0/manifest.json
I'd expect `composer req phpunit` to produce the same as `composer req test`.
This also implements https://github.com/symfony/symfony/issues/27037#issuecomment-387280742
There is no need to provide a default config when using symfony 4.1.
Here is a diff between recipes v3.3 and v4.1 for the phpunit-bridge:
```diff
diff -r symfony/phpunit-bridge/3.3/bin/phpunit symfony/phpunit-bridge/4.1/bin/phpunit
9c9
<     putenv('SYMFONY_PHPUNIT_REMOVE=symfony/yaml');
---
>     putenv('SYMFONY_PHPUNIT_REMOVE=');
Only in symfony/phpunit-bridge/3.3: config/services_test.yaml
diff -r symfony/phpunit-bridge/3.3/manifest.json symfony/phpunit-bridge/4.1/manifest.json
4d3
<         "config/": "%CONFIG_DIR%/",
```
> Alias "phpunit" to test-pack, remove config when installing v4.1 of phpunit-bridge

- lexik/jwt-authentication-bundle/2.5/config/packages/lexik_jwt_authentication.yaml
- lexik/jwt-authentication-bundle/2.5/manifest.json
The change requiring a new version of the recipe is that the `public_key_path` and `private_key_path` have been renamed to `public_key` and `secret_key`.
Motivation for this naming change is that they now both accept a raw key as value, which allows storing the raw key itself as an env var and configure the bundle like `secret_key: %env(JWT_PRIVATE_KEY)%` or use whatever custom env var processor to resolve the raw key (I need some feedbacks before using this for the recipe config). Additionally HMAC support was added, which requires only `secret_key` to be set with a raw secret string.
Lastly, only one of the key is required by the config tree (think SSO, server needs the secret key and clients need the public one, no side …
> [lexik_jwt_authentication] Add recipe for v2.5

- symfony/framework-bundle/3.3/config/services.yaml
- symfony/routing/3.3/config/routes.yaml
Fixes https://github.com/symfony/symfony-docs/issues/9285
> Add intro note to services.yaml and routes.yaml

- symfony/phpunit-bridge/4.1/phpunit.xml.dist
Since default `SYMFONY_PHPUNIT_VERSION` is set to 6.5 in `bin/phpunit`, it should be used also in XSI namespace to allow for example `showOnlySummary` in text code coverage output.
> Updated PHPUnit version in XSI namespace

- sensio/framework-extra-bundle/5.2/config/packages/sensio_framework_extra.yaml
- sensio/framework-extra-bundle/5.2/manifest.json
see sensiolabs/SensioFrameworkExtraBundle#562
Credits go to @mehranhadidi who made me aware of this in the Symfony Slack.
> disable route annotations with SensioFrameworkExtraBundle 5.2

- symfony/webpack-encore-pack/1.0/config/packages/assets.yaml
- symfony/webpack-encore-pack/1.0/manifest.json
- symfony/webpack-encore-pack/1.0/webpack.config.js
Let's enable versioned assets by default?
Related to https://github.com/symfony/webpack-encore-pack/pull/1
> [webpack-encore] use versioned assets

- symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml
yamllint: too many spaces after colon (colons)
Same like #436, but for the `prod` env.
Sorry for creating 2 Pull-Requests, but used the WYSIWYG-Editor on github.com for this...
> prevent yaml lint error

- symfony/validator/4.1/config/packages/validator.yaml
- symfony/validator/4.1/manifest.json
https://github.com/symfony/symfony/pull/25478#issuecomment-351309384
> enable HTML5 e-mail validation

- symfony/webpack-encore-pack/1.0/assets/css/app.css
- symfony/webpack-encore-pack/1.0/assets/js/app.js
- symfony/webpack-encore-pack/1.0/package.json
- symfony/webpack-encore-pack/1.0/webpack.config.js
Re-reading the default webpack.config.js file for clarity. I'm also updating the documentation at the moment, and will base those changes off of this.
> Proofreading webpack.config.js for clarity

- symfony/phpunit-bridge/3.3/bin/phpunit
- symfony/phpunit-bridge/4.1/bin/phpunit
Until now, I've been advocating that peoples' CI should fail whenever a deprecation is reported.
But when a vendor throws a deprecation, sometime, it's not your fault and you can't do anything about it (except contributing back to the project, which is good for OSS!)
Talking on Slack, @greg0ire convinced me we can do this change: by setting `SYMFONY_DEPRECATIONS_HELPER` to `999999` by default, we make ppls' CI green (when they don't raise more than 1M deprecations.)
And it still makes the deprecation report visible on the tests' output so that ppl still have some incentive to fix them.
Fixes https://github.com/symfony/symfony/issues/27936
> [phpunit-bridge] default to not failing on deprecations

- symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml
Only deprecations are logged at "INFO" level on the "php" channel.
Let's write them down by default in prod, since deprecations that happen in prod may be seen only there (typically when you don't have 100% test coverage, do you?)
> [monolog-bundle] log deprecations by default, in a dedicated log file

- symfony/webpack-encore-pack/1.0/package.json
Under yarn/npm versioning rules, the new `0.20.*` versions  weren't installable by default,  see also: 
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
Its pretty much the same as composer versioning, as in it wont bump minor versions in pre `1.0.0` versioning.
> Allow installation of latest encore version

- symfony/routing/3.3/config/packages/test/routing.yaml
- symfony/routing/4.0/config/packages/test/routing.yaml
- symfony/routing/4.2/config/packages/test/routing.yaml
Related issue https://github.com/symfony/recipes/issues/454
> Set framework.router.strict_requirements to true in test env by default

- symfony/translation/3.3/config/packages/translation.yaml
- symfony/twig-bundle/3.3/config/packages/twig.yaml
Fix https://github.com/symfony/recipes/pull/416#issuecomment-404230767
> Use default_path instead of paths for Twig and Translator config

- README.rst
As said in https://github.com/symfony/recipes/pull/447#issuecomment-418300427 I think we need to revert this commit. The readme does not describe the format of the resulting `composer.json` section, but describes how you need to define the configurator in the `manifest.json` file of a recipe.
> revert #447

- symfony/framework-bundle/4.2/public/index.php
The current condition does not guarantee we do not load `.env` in production. We should tweak whether the comment or the condition to `if (!isset($_SERVER['APP_ENV']) || 'prod' === $_SERVER['APP_ENV'])`. Or maybe remove this comment at all? It's pretty obvious.
> Slightly tweak the comment

- symfony/framework-bundle/3.3/public/index.php
- symfony/framework-bundle/4.2/public/index.php
When the builtin PHP web server is used, env vars are only available in `$_ENV`, not in `$_SERVER` (see https://bugs.php.net/bug.php?id=67808).
This is especially annoying when testing an app with Panther because, by default, it automatically boots the app using the integrated PHP web server, consequently env vars defined in `phpunit.xml` aren't inherited, and the app executed using the `dev` env instead of the `test` one.
This PR fixes this problem.
> [FWBundle] $_ENV fallback (needed for Panther)

- behat/symfony2-extension/2.1/features/bootstrap/bootstrap.php
- phpunit/phpunit/4.7/.env.test
- phpunit/phpunit/4.7/manifest.json
- phpunit/phpunit/4.7/phpunit.xml.dist
- phpunit/phpunit/4.7/tests/bootstrap.php
- symfony/console/3.3/bin/console
- symfony/flex/1.0/.env
- symfony/flex/1.0/manifest.json
- symfony/framework-bundle/3.3/public/index.php
- symfony/framework-bundle/3.3/src/Kernel.php
- symfony/framework-bundle/4.2/manifest.json
- symfony/framework-bundle/4.2/public/index.php
- symfony/framework-bundle/4.2/src/Kernel.php
- symfony/phpunit-bridge/3.3/.env.test
- symfony/phpunit-bridge/3.3/bin/phpunit
- symfony/phpunit-bridge/3.3/manifest.json
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
- symfony/phpunit-bridge/4.1/.env.test
- symfony/phpunit-bridge/4.1/bin/phpunit
- symfony/phpunit-bridge/4.1/manifest.json
- symfony/phpunit-bridge/4.1/phpunit.xml.dist
This PR is an alternative to #466 and replaces #479.
It needs https://github.com/symfony/symfony/pull/29129 to work with 4.2.
What we have here:
- Dotenv is configured to load `.env` < `.env.local` < `.env.$env` < `.env.$env.local` (only the 1st is required, see PR linked above)
- this works starting with Symfony 3.4 and uses an optimized code starting with 4.2 (removing the doc-split hell)
- the loading logic is factorized in a new static `Kernel::bootstrapEnv()` method
- the CLI accepts and *consumes* `--env` & `--no-debug` (see `Kernel::bootstrapCliEnv()`, fixes https://github.com/symfony/symfony/issues/23343)
- `.env` files are loaded for tests (fixes https://github.com/symfony/flex/issues/317, …
> Allow to override .env files per env

- symfony/flex/1.0/.env.dist
- symfony/framework-bundle/3.3/manifest.json
In #481, the symfony/flex 1.0 recipe was changed so that the user gets a `.env` file and NOT a `.env.dist`. The gitignore recipe for FWBundle 4.2 was updated, but not 3.3.
Cheers!
> Fix recipe: make consistent with symfony/flex 1.0 new env handling

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml
This change will allow tests to be more easily run with `debug=false`.
Ref: https://github.com/symfony/recipes/pull/242
> [DoctrineBundle] set auto_generate_proxy_classes to true, false in prod

- symfony/webpack-encore-bundle/1.0/package.json
Needed so users get the latest version - `^0.21.0` will only allow for `0.21.*`. We ultimately need a stable Encore release to ease needing to always make this change.
Thanks!
> Bumping encore version

- symfony/console/3.3/bin/console
- symfony/framework-bundle/3.3/public/index.php
- symfony/framework-bundle/4.2/public/index.php
Tries to fix https://github.com/symfony/recipes/pull/481#issuecomment-440981814 by ensuring debug is cast to a bool, for those projects that may have enabled strict typing.
This restores the old behaviour which had a cast.
I am unsure if `src/.bootstrap.php` should enforce the bool, or if should be cast at the last moment, like in this PS. please advise!
> cast debug to boolean when creating kernel

- symfony/mercure-bundle/0.1/config/packages/mercure.yaml
- symfony/mercure-bundle/0.1/manifest.json
> Add MercureBundle recipe

- .travis.yml
> Fix the Travis build with multiple recipes

- api-platform/admin-pack/1.0/assets/js/admin.js
- api-platform/admin-pack/1.0/config/routes/api_platform_admin.yaml
- api-platform/admin-pack/1.0/manifest.json
- api-platform/admin-pack/1.0/post-install.txt
- api-platform/admin-pack/1.0/templates/admin.html.twig
- symfony/webpack-encore-bundle/1.0/webpack.config.js
This PR makes it easy to use [API Platform Admin](https://api-platform.com/docs/admin) in a traditional Symfony app (an app using Twig).
The recipe installs Webpack Encore and API Platform (using their respective packs) and generate a Twig template, a route and the appropriate code to load the admin in a standard Symfony page. 
It works in a different way than in the "official" distribution of API Platform:
* in API Platform, the admin is a standalone Progressive Web App that must be hosted as a static website (using GitHub Page, Netlify or similar solutions)
* when using this recipe, the React component is loaded directly inside the existing Symfony application, through a Twig template (so it is not installable as a PWA, but …
> Add a recipe for API Platform Admin

- sensiolabs/security-checker/4.0/config/packages/security_checker.yaml
Using autowire & autoconfigure in `security_checker.yaml`
This made for consistency with main `config/services.yaml` style and following the latest trends.
Moved from https://github.com/symfony/demo/pull/898
> Using autowire in security_checker.yaml

- symfony/webpack-encore-bundle/1.0/assets/js/app.js
Some optimization when we init encore with Flex. We can use ```let``` instruction because webpack transpile that. I think that gitignore is not needed because css and js folder exists at creation. If the developer change that folder, it's his responsability to create this file.
> Optimize Encore Init

- symfony/console/3.3/bin/console
- symfony/flex/1.0/.env
- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/3.3/manifest.json
- symfony/framework-bundle/4.2/config/bootstrap.php
- symfony/framework-bundle/4.2/manifest.json
This PR provides a nice experience where `.env` files are "always" loaded.
That means their purpose is easy to reason about: the committed files define the defaults (`.env` especially) - and `.env.local` defines local overrides.
A new `.env.local.php` is provided for prod, so that performance is not affected.
When `.env.local.php` is found, other .env files are ignored.
On the deployement side, this means it should be much easier to deal with `.env` files for people that can't easilly deal with real env vars:
- if you use real env vars they always win
- logically, `.env` files are always loaded (to define defaults)
- on prod, one can dump a `.env.local.php` file for max performance
The plan is to add a new flex command to …
> Always load vars defined in .env files, providing .env.local.php for prod

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
Hi people!
Fixes #512 
This happened after #501 was merged. Previously, code at the top of `bootstrap.php` guaranteed that the `$_SERVER['APP_ENV']` key always existed. After that was removed, the code at the bottom needed to be updated to account for this.
I tested that this does fix the undefined index problem when using phpunit.
Cheers!
> Allowing APP_ENV to be an empty index

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
One more tweak after #513 
It's an edge-case, but when APP_ENV is set to an empty string
```
APP_ENV='' php bin/console
```
Before `$_SERVER['APP_ENV']` would be an empty string, after it would be `dev`. 
Or, maybe we decide that the current behavior IS the correct behavior. It's an edge-case either way.
> minor tweak - if APP_ENV is an empty string, this defaults it back to dev

- easycorp/easyadmin-bundle/2.0/config/packages/easy_admin.yaml
- easycorp/easyadmin-bundle/2.0/config/routes/easy_admin.yaml
- easycorp/easyadmin-bundle/2.0/manifest.json
The only real change is the `/config/routes/easy_admin.yaml` file which now points to a different controller (because the new one extends from AbstractController instead of the deprecated Controller).
> Added a new recipe for EasyAdmin 2.x

- symfony/webpack-encore-bundle/1.0/webpack.config.js
Don't we need adding .`.splitEntryChunks()` as pointed in docs? See https://github.com/symfony/webpack-encore-bundle#usage
> Add .splitEntryChunks() to webpack.config.js

- symfony/framework-bundle/4.2/src/Kernel.php
It's common to add a 'wildcard' route to an application that looks like
a CMS. Usually the route has the following path `/{slug}`.
But with the current routes loading order, the 'dev' routing is loaded
after regular routes. In previous SF versions, dev routing was loaded
first. This PR retores this behavior.
> Load routes for specific env first

- symfony/framework-bundle/4.2/src/Kernel.php
Symfony 4 requires PHP 7.1 so I think that the recipe can use features from 7.1. Otherwise I was doing those changes manually when creating a new SF project.
What do you think?
> symfony/framework-bundle 4.2 can use PHP 7.1 features

- symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
See symfony/webpack-encore-bundle#12
This is only available in 1.2, but I don't see a good reason to duplicate the recipe - it's an opt-in feature (so it will always be commented-out by default) and even if you, somehow, installed an older version today, you will now be aware of this feature.
Thanks!
> Documenting the WebpackEncoreBundle caching option

- symfony/console/3.3/bin/console
- symfony/framework-bundle/4.2/public/index.php
Changed invocation of the Kernel according to the feature from symfony/symfony#30651.
This removes the need for a `composer.json` to define the project folder when using the framework bundle.
> Add project path to app Kernel instanciation

- php-http/httplug-pack/1.0/manifest.json
symfony/http-client will be the new default for `http-client` (and I don't think we need one for `http`)
> Remove http&http-client aliases from php-http/httplug-pack

- symfony/webpack-encore-bundle/1.0/package.json
- symfony/webpack-encore-bundle/1.0/webpack.config.js
This PR is related to https://github.com/symfony/webpack-encore/pull/545 and must not be merged until a new version of Encore is released (0.26.x).
Quick summary: we will soon set the `useBuiltIns` option of `@babel/preset-env` to `false` instead of `entry` by default (which makes it not handle `core-js` polyfills anymore).
This is needed because the other values (`entry` and `usage`) require the users to at least add `core-js` to their projects and specify its version in `@babel/preset-env`'s settings.
With this update the recipe will automatically require `core-js@3` and configure `@babel/preset-env` so polyfills are automatically added when/where they are needed (`useBuiltIns: 'usage'` and `corejs: 3`).
/cc @weaverryan
> [Encore] Make @babel/preset-env use polyfills by default

- phpunit/phpunit/4.7/manifest.json
> Add ".phpunit.result.cache" to .gitignore

- phpunit/phpunit/4.7/phpunit.xml.dist
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
> Change PHPUnit env to server

- symfony/framework-bundle/4.2/src/Kernel.php
References #555 and symfony/symfony#30651
This defines the project directory without looking for the `composer.json`.
> Add project dir to framework bundle

- symfony/framework-bundle/4.2/config/bootstrap.php
When dumping the env using Flex 1.2 ``dump-env`` the getenv function does no longer work for these variables.
This is a quick fix just like it is done in ``DotEnv::populate``, but might need further review.
> Fix getenv() not working with .env.local.php

- symfony/console/3.3/bin/console
Add a CLI guard in `bin/console`. This file is not meant to be executed in another context than CLI, as such it may be a good idea to bail out early when it's not the case. I don't think it's a necessity, but it can be seen as an inexpensive additional guard like done in most CLI applications including Composer.
> Add a CLI guard to the bin/console

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
Reverts #540, fixes https://github.com/symfony/recipes/issues/532#issuecomment-481302280
> Populate $_SERVER with $_ENV

- symfony/webpack-encore-bundle/1.0/package.json
Btw, we *are* looking at a proper, stable of Encore (which would allow us to avoid needing to do this) when Webpack 5 is released.
Cheers!
> Bumping Encore deps for 0.27.0

- symfony/webpack-encore-bundle/1.0/config/packages/prod/webpack_encore.yaml
- symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
We made a mistake in #541 
We should only enable cache when `%kernel.debug%` is NOT true. 
#eu-fossa
> [Webpack encore] Enable cache only in prod

- symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
This PR makes two changes
1) update documentation for previous feature allowing output_path to be false
2) update documentation for new feature to set the value fo crossorigin attribute if PR https://github.com/symfony/webpack-encore-bundle/pull/56 is accepted
> [webpack-encore-bundle] - update comments in default recipe for new features

- symfony/amazon-mailer/4.3/manifest.json
- symfony/mailchimp-mailer/4.3/manifest.json
- symfony/mailgun-mailer/4.3/manifest.json
- symfony/postmark-mailer/4.3/manifest.json
- symfony/sendgrid-mailer/4.3/manifest.json
I've not added `gmail` as it should not be used in production (so let's avoid it here).
> Add recipes from third-party mailer transports

- symfony/security-bundle/3.3/config/packages/security.yaml
I think it's better to link to the authentication system, than give a few examples here. form_login is especially not useful, as we recommend using Guard instead of this and *simply* uncommenting this is not nearly enough to get it working anyways.
Cheers!
> Simplifying links to authentication in security.yaml

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
Following this [discussion](https://github.com/symfony/symfony/issues/31497#issuecomment-492616894) I removed the default database URL in parameters section because a default value is already defined in the `.env`
> Remove default database URL as it already defined in .env

- lexik/jwt-authentication-bundle/2.3/manifest.json
- lexik/jwt-authentication-bundle/2.5/manifest.json
As it's the de-facto bundle for JWT authentication.
> Add "jwt" alias for lexik/jwt-authentication-bundle

- symfony/validator/4.1/config/packages/test/validator.yaml
See https://github.com/symfony/symfony/issues/31756
> Fix disabling not_compromised_password validation

- symfony/google-mailer/4.3/manifest.json
It wasn't added in #587 but I think this is a missing piece. If it's not recommended to use Gmail on production, let's add a note about it because not having a recipe for this does not mean devs won't use it on production.
> RFC Create a recipe for Google mailer transport

- symfony/webpack-encore-bundle/1.0/webpack.config.js
With this, we directly fix the error: 
> Encore.setOutputPath() cannot be called yet because the runtime environment
doesn't appear to be configured. Make sure you're using the encore executable
or call Encore.configureRuntimeEnvironment() first if you're purposely not
calling Encore directly.
when using Encore/Webpack without the `encore` command (`npm run encore ...`).
This is useful when:
- using tools that depends of `webpack.config.js`, like ESLint with the import plugin, Karma, ...
- using an IDE with Webpack integration
This doesn't break anything if you use `encore` command, since it already configure the runtime environment.
See:
- https://symfony.com/doc/current/frontend/encore/faq.html#how-do-i-integrate-my-encore-c …
> Encore: configure runtime environment if not already configured

- symfony/validator/4.3/config/packages/test/validator.yaml
This was renamed https://github.com/symfony/symfony/commit/ecfccc6ef011b20390a9ae9a70d5c7e8e2ddf83e#diff-5e7347edce37c5886ec67b7ba02f3a9c
Caught by the MakerBundle test suite
> Fixing validator option name - not_compromised_password

- symfony/monolog-bundle/3.3/config/packages/dev/monolog.yaml
- symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml
- symfony/monolog-bundle/3.3/config/packages/test/monolog.yaml
- symfony/monolog-bundle/3.3/manifest.json
This uses `excluded_http_codes` instead of `excluded_404s`, which is more flexible (and `excluded_404s` is deprecated in the next, unreleased version of MonologBundle).
> MonologBundle: use excluded_http_codes

- symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
When using the `%kernel.debug%` value for the `cache` parameter means the entrypoints will be cached when debug is true, where actually it should be the reverse. This currently causes issues in development mode, especially when using integrity hashes, since the integrity hash is cached with the entrypoints and it won't match the content of the assets if they changed. So I think this value should by default be set to `false`, where the developer can then decide if they want to enable it in production (an alternative option is to create another config file in the `prod` folder where this value defaults to `true`)
> [WebpackEncoreBundle] Don't use kernel.debug for the cache parameter

- symfony/phpunit-bridge/4.3/bin/phpunit
- symfony/phpunit-bridge/4.3/phpunit.xml.dist
#584 borrowed from v3.3 while it should have from 4.1.
Fixes https://github.com/symfony/symfony/issues/31816
> [symfony/phpunit-bridge] Sync v4.3 with v4.1

- symfony/google-mailer/4.3/manifest.json
Fixed `MAILER_DSN` value for google-mailer. I changed `google` DSN host code key by `gmail` as specified in `Symfony\Component\Mailer\Transport` class.
> [symfony/google-mailer] Fix gmail DSN host code key.

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
| Doc issue/PR  | https://github.com/symfony/flex/issues/516b
Fixes the issue where by `.env.local.php` was not overridable by real env vars.
> ensure $_ENV is contains real env vars from $_SERVER , or defaults from .env.local.php

- symfony/amazon-mailer/4.3/manifest.json
- symfony/mailchimp-mailer/4.3/manifest.json
- symfony/mailgun-mailer/4.3/manifest.json
- symfony/postmark-mailer/4.3/manifest.json
- symfony/sendgrid-mailer/4.3/manifest.json
It's cool how all the mailers embed other environment variables inside of them. But actually, I got confused by this - I didn't think about how I could define `SENDGRID_KEY` as its own env var, and then leave `MAILER_DSN` alone. Why not also add the `SENDGRID_KEY` as an env var? If we agree, I'll do the same for all the mailer configs.
> RFC: explicitly adding mailer env vars

- friendsofphp/php-cs-fixer/2.2/.php_cs.dist
Provide a default Finder configuration matching the Flex directory structure. Then PHP-CS-Fixer can be called with `vendor/bin/php-cs-fixer fix` can be called directly.
> [cs-fixer] Configure properly the default finder

- symfony/framework-bundle/3.3/config/packages/framework.yaml
- symfony/framework-bundle/4.2/config/packages/framework.yaml
- symfony/translation/3.3/config/packages/translation.yaml
- symfony/translation/3.3/manifest.json
`default_locale` shouldn't be set both in `framework.yaml` and in translation. And the parameter is useless.
> [symfony/translation] Remove confusing commented value

- symfony/webpack-encore-bundle/1.0/webpack.config.js
We do the same for `enableVersioning()`
> Enable integrity hashes on production only by default

- phpunit/phpunit/4.7/.env.test
- symfony/phpunit-bridge/3.3/.env.test
- symfony/phpunit-bridge/4.1/.env.test
Since dollar sign "represents" S letter, `s$cretf0rt3st` does not make sense.
It drives me mad every time we start new project and I see it on code review :joy: 
> Proper APP_SECRET default value

- symfony/swiftmailer-bundle/2.5/manifest.json
I think it makes sense. When a user of the Symfony framework asks for Swiftmailer, they most likely want the bundle too.
> Add "swiftmailer" alias for symfony/swiftmailer-bundle

- symfony/webpack-encore-bundle/1.0/package.json
This PR adds `regenerator-runtime` to the npm dependencies installed by the Webpack Encore Bundle.
The reason behind this change is that `@babel/preset-env` detects `async` functions usage and compile them in a way that they can't be used if you don't also import the `regenerator-runtime`.
With the current default Babel settings (`useBuiltIns: 'usage'`), `@babel/preset-env` will automatically add this import to the entries requiring it, but unless you already have `regenerator-runtime` in your dependencies you'll get an error message asking you to `npm install regenerator-runtime/runtime` (which is wrong, but that's another story).
I can't see any downside adding it by default since the worst case is …
> [Encore] Add regenerator-runtime to default dependencies

- symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
Otherwise I get:
```
Invalid type for path "webpack_encore.cache". Expected boolean, but got string.
Hint: Enable caching of the entry point file(s)
```
In the `prod` file, everything is correct.
cc @weaverryan
> Use boolean instead of string.

- phpunit/phpunit/4.7/phpunit.xml.dist
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
- symfony/phpunit-bridge/4.1/phpunit.xml.dist
| Doc issue/PR  | none
PHPUnit moved its documentation to readthedocs.io since a while
> fix phpunit documentation link

- symfony/mercure-bundle/0.1/manifest.json
Needs https://github.com/symfony/flex/pull/128
> Add Docker support for the Mercure recipe

- symfony/phpunit-bridge/4.1/phpunit.xml.dist
| Doc issue/PR  | none should be needed   
6.5 if EOL since February. Is the philosophy that we stay on the oldest-supported... or stay on the newest (and I should bump to 8.2?)
> bumping to php 7.5 to stay on supported version

- symfony/webpack-encore-bundle/1.0/package.json
Needed since we're still on the 0.X releases.
0.28.0 is released - so this can be merged now.
> Bumping Encore version to 0.28.0

- symfony/messenger/4.1/manifest.json
- symfony/messenger/4.3/manifest.json
Requires dunglas/symfony-docker-skeleton#5 and symfony/flex#128.
It's like the PR #113 for doctrine-bundle
> [messenger] Docker support

- symfony/mercure-bundle/0.1/config/packages/mercure.yaml
- symfony/mercure-bundle/0.1/manifest.json
Renamed the confusing `MERCURE_JWT_SECRET` to `MERCURE_JWT_TOKEN`. Should be okay according to https://github.com/symfony/recipes/pull/525#issuecomment-523363694
Removed default values for the env vars, in line with https://github.com/symfony/recipes/pull/588
> Simplify the MercureBundle recipe

- symfony/amazon-mailer/4.4/manifest.json
- symfony/google-mailer/4.4/manifest.json
- symfony/mailchimp-mailer/4.4/manifest.json
- symfony/mailgun-mailer/4.4/manifest.json
- symfony/postmark-mailer/4.4/manifest.json
- symfony/sendgrid-mailer/4.4/manifest.json
> Fix Mailer DSNs for 4.4

- symfony/monolog-bundle/3.1/config/packages/dev/monolog.yaml
> [MonologBundle] Added (commented) configuration for log format

- symfony/amazon-mailer/4.3/manifest.json
- symfony/amazon-mailer/4.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony/issues/33827
> Explicitly mention AWS region

- nyholm/psr7/1.0/manifest.json
This is a follow up on #546. I forgot to add some aliases.
> Add PSR7 and PSR17 aliases

- phpunit/phpunit/4.7/phpunit.xml.dist
- symfony/phpunit-bridge/3.3/phpunit.xml.dist
- symfony/phpunit-bridge/4.1/phpunit.xml.dist
Using the local `phpunit.xsd` file guarantees we use the exact version that is installed. It also improves DX with PhpStorm as it becomes able to validate `phpunit.xml` without manually registering XSD file's URI.
> Make use of the local phpunit.xsd

- symfony/mercure-bundle/0.1/manifest.json
The hub URL changed in Mercure 0.8.
> [mercure] v0.8 compatibility

- symfony/mercure-bundle/0.1/config/packages/mercure.yaml
This option will be required by https://github.com/symfony/mercure-bundle/pull/13
> Add enable_profiler option on mercure-bundle

- symfony/mercure-bundle/0.2/config/packages/mercure.yaml
- symfony/mercure-bundle/0.2/manifest.json
> [Mercure] Fix enable_profiler node position

- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/1.6/manifest.json
I've spent hours of debugging because the db driver was set differently in two places: the yaml and the .env files.
Actually, we don't need the duplication at all. Let's favor the `.env` since it is now always loaded.
> [doctrine/doctrine-bundle] dont duplicate the db settings

- symfony/framework-bundle/4.4/config/routes/dev/framework.yaml
- symfony/twig-bundle/4.4/config/routes
| Doc issue/PR  | N/A    
AFAIU, the controller for this route is deprecated in favor of the `HttpKernel` one registered through the fwb recipe. So new projects starting with Twig 4.4 should not start with this deprecated route, and use the fwb one instead.
> [Fwb][TwigBundle] Remove Twig Preview controller routing in favor of fwb

- symfony/twig-bundle/3.3/config/packages/test/twig.yaml
- symfony/twig-bundle/4.4/config/packages/test
> Set twig.strict_variables to true in test env by default

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
I'm not sure if this is useful for other people - but I'm sharing it, and you can just reject it if not :)
I got here because I'm building a docker image, with all my code, and optimising it for prod run time, so I've run `composer dump-env prod` - but I want to use the same image to run my tests - so I'm testing in the prod system. But actually this is easy to repeat in your dev environment, if you dump prod, and leave it there, you no longer get `.env.dev` loaded.
Basically if `.env.local.php` exists, the environment no longer properly switches, as the `.env.$env` files are not used. This PR changes this so that the correct env is always loaded.
> Allow changing environement when `.env.local.php` exists.

- symfony/framework-bundle/3.3/src/Kernel.php
- symfony/framework-bundle/4.2/src/Kernel.php
Double-star discovery is a slow path, yet no recipes use any higher level - and I don't see why one would need this.
Let's gain some perf with this change.
> Dont look recursively into per-env folders

- symfony/framework-bundle/4.2/src/Kernel.php
Closes https://github.com/symfony/symfony/issues/34368
Works around a memory leak reported in https://bugs.php.net/76982 and explained at https://jolicode.com/blog/you-may-have-memory-leaking-from-php-7-and-symfony-tests
Helps with long-running scripts (workers) that currently can break when the cache is  cleared separately (on dev mostly.)
> [framework-bundle] enable "inline_factories", disable "inline_class_loader" when PHP 7.4 preloading is used

- symfony/framework-bundle/3.3/config/packages/cache.yaml
| Doc issue/PR  | not needed
A user I talked to recently didn't realize that the "app" cache should persist between deploys (i.e. not be cleared/reset like the "system" cache). This is meant to clarify that.
Cheers!
> Clarifying the purpose of the "app" cache

- symfony/mailer/4.3/manifest.json
- symfony/swiftmailer-bundle/2.5/manifest.json
To be merged just after the 5.0 release.
> Move the mail and mailer aliases to symfony/mailer instead of swiftmailer

- doctrine/doctrine-bundle/1.6/manifest.json
We should add charset on example DSN otherwise the charset option of `doctrine.yaml` leads to an error
> [DoctrineBundle] Add charset option to postgres example

- doctrine/doctrine-bundle/1.12/config/packages/prod/doctrine.yaml
This change is required since we reverted some changes on doctrine-bundle to restore non-persistent caches for non-prod environments: https://github.com/doctrine/DoctrineBundle/pull/1073
This fixes some issues that were reported:
https://github.com/symfony/recipes/issues/688
https://github.com/doctrine/DoctrineBundle/issues/1069
https://github.com/doctrine/migrations/issues/873
Tested this on symfony-demo with doctrine-bundle 1.12.x
```
it@7444b85a5a96:/var/www/symfony-demo  (master) $ bin/console debug:container doctrine.orm.default_metadata_cache --env=prod --show-arguments
// This service is a private alias for the service                                                                     
// …
```
> Fix doctrine-bundle recipe for prod caching pools

- symfony/webpack-encore-bundle/1.0/package.json
- symfony/webpack-encore-bundle/1.0/webpack.config.js
Use `configureBabelPresetEnv()` introduced in symfony/webpack-encore#642 instead of `configureBabel()`.
> Use configureBabelPresetEnv() in webpack.config.js

- symfony/framework-bundle/4.2/src/Kernel.php
- symfony/framework-bundle/5.1/src/Kernel.php
Ppl that care about the extra perf this would provide would better enable preloading instead on PHP 7.4.
This will prevent issues with CLI vs FPM with different config for opcache.preload.
> Dont inline_class_loader on PHP 7.4

- symfony/framework-bundle/5.1/src/Kernel.php
Requires https://github.com/symfony/symfony/pull/34873
Removes also the multi file-extensions support. Nobody needs that by default AFAIK. Ppl that do can easily add it back.
> Simplify the default Kernel

- symfony/framework-bundle/4.2/src/Kernel.php
We forgot about it, but setting inline_class_loader to true allows bypassing `DebugClassLoader` in debug mode, which provides a significant DX improvement, even on PHP 7.4+
> Enable inline_class_loader in debug mode

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
> Allow missing APP_ENV in .env.local.php

- phpunit/phpunit/4.7/phpunit.xml.dist
- symfony/phpunit-bridge/4.1/phpunit.xml.dist
After noticing slow coverage collection on our jenkins server for our symfony project, i noticed after some time that we were missing the on the whitelist configuration the processUncoveredFilesFromWhitelist attribute. I tried to backtrace why this configuration was missing and realized that this might come from the phpunit flex recipe. So here we go with the fix.
Fixes issues with slow coverage collection mentioned here:  
https://github.com/sebastianbergmann/phpunit/issues/2489  
Also the documentation already includes the configuration:  
https://symfony.com/doc/4.4/create_framework/unit_testing.html
https://symfony.com/doc/current/create_framework/unit_testing.html
> Align code coverage settings with documentation

- doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml
IMHO this is rather useful to look into when debugging. Assumed disabling is more easy, then enabling ... yet the proposed default should be best of both.
Hinted in https://github.com/symfony/symfony/issues/18235#issuecomment-562600074
> enable query profiling for debug

- symfony/monolog-bundle/3.3/config/packages/test/monolog.yaml
I'd argue by default you need the full application logs when running (or writing) tests.
> Disable logging for test env

- symfony/framework-bundle/3.3/manifest.json
- symfony/framework-bundle/4.2/manifest.json
Fixes https://github.com/symfony/recipes/pull/494#discussion_r372441028
Actually the direct translation for the old `explode(',', "localhost,example.com")` into regexp would be `['^localhost$', '^example\.com$']` (like in [the docs](https://symfony.com/doc/3.4/reference/configuration/framework.html#trusted-hosts)), but this env var is expected as a single string (by [public/index.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/public/index.php)), hence `'^localhost$|^example\.com$'` (JSON-encoded in the file).
Equivalent alternative: `'^(?:localhost|example\.com)$'` (i.e. `"'^(?:localhost|example\\.com)$'"`), but not sure if better
> Fix TRUSTED_HOSTS regexp example

- doctrine/annotations/1.0/config/routes/annotations.yaml
Since this will be allowed by https://github.com/symfony/symfony/pull/35560 and allows writting single-file apps in the kernel, for microapps.
> Look at the Kernel for annotations

- symfony/security-bundle/3.3/config/packages/security.yaml
- symfony/security-bundle/4.4/config/packages/security.yaml
| Doc issue/PR  | ~
The name of the default memory provider has always been confusing to me, and keep being confusing for my trainees, training after training.
Here an attempt to clarify that this is a name and not the type.
Also, having multiple providers without making explicite the one used by the firewall throws from Symfony 4, so I propose to reflect that in the recipe (maybe we should do so in the 3.3 recipe too).
If you agree I'll update the docs accordingly. Thanks!
> [Security] Renamed in memory provider

- symfony/phpunit-bridge/3.3/config/services_test.yaml
- symfony/phpunit-bridge/3.3/manifest.json
Since Symfony 4.1, you can fetch private services from a test using
a special method - creating public aliases is not required anymore.
| Doc issue/PR  | Docs already mention this https://symfony.com/doc/current/testing.html#accessing-the-container
I'm removing this instead of creating a new version of the recipe mostly for simplicity. The only version that would still need this and is NOT EOL is 3.4. This recipe change would only affect people installing phpunit-bridge into 3.4 today - I think it's worth just keeping the one recipe version. But I can split into a newer version if we want.
Cheers!
> removing services_test.yaml from symfony/phpunit-bridge recipe

- doctrine/doctrine-migrations-bundle/2.2/config/packages/doctrine_migrations.yaml
- doctrine/doctrine-migrations-bundle/2.2/manifest.json
Closes https://github.com/symfony/recipes/issues/718
> Recipe for upcoming doctrine/migrations 3.0 and 2.2

- symfony/framework-bundle/5.1/config/routes.php
- symfony/framework-bundle/5.1/config/services.php
- symfony/framework-bundle/5.1/config/services.yaml
- symfony/framework-bundle/5.1/src/Kernel.php
- symfony/routing/5.1/config/packages
- symfony/routing/5.1/manifest.json
This PR is here to demonstrate the new capabilities of Symfony 5.1.
Basically, we can now develop a full Symfony app in a single file, like "microframeworks" 
No `services.yaml`, no `routes.yaml` here.
> Use PHP to define the services and routes of the app

- symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml
I suggest that we comment the logging of deprecations in production. Depending on your application, it can fill your logs pretty fast, and we don't want such a thing to happen by default. Logging deprecations in prod should be a conscious decision IMHO.
> Comment deprecation logs (Monolog)

- symfony/mailgun-mailer/4.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/13154
Just got a hard time to get SMTP working with european servers from Mailgun. It was unclear how to configure the EU host (ie. should I change the `@default` host? Should I add another config?). I think showing the existence of this parameter in the recipe by default would help a lot.
> Show region parameter in Mailgun mailer DSN

- symfony/framework-bundle/5.1/src/Kernel.php
This class has been reverted in 5.1.
> [symfony/framework-bundle] revert use of RoutingConfigurator from FrameworkBundle

- symfony/framework-bundle/3.3/config/bootstrap.php
- symfony/framework-bundle/4.2/config/bootstrap.php
This fixes populating the `SYMFONY_DOTENV_VARS` env var.
The overhead of loading the `Dotenv` class is removed by using preloading if one really cares. And the overhead of running the method is minimal IMHO.
This already what happens on the recipe for master btw.
> Use Dotenv::populate() to define the dumped env vars

- symfony/mattermost-notifier/5.1/manifest.json
Mattermost notifier: add documentation link and use `CHANNEL_ID` as example value for channel, to avoid confusions with the parameter value needed there
> Update mattermost-notifier: add documentation link

- symfony/routing/5.1/config/packages/prod
- symfony/routing/5.1/config/packages/routing.yaml
- symfony/routing/5.1/config/routes.yaml
- symfony/routing/5.1/manifest.json
| Doc issue/PR  | N/A    
Follows https://github.com/symfony/symfony/pull/35281
> [Router] Add recipe for 5.1 router default URI config

- symfony/security-bundle/5.1/config/packages/security.yaml
- symfony/security-bundle/5.1/manifest.json
Following https://github.com/symfony/symfony/pull/36574
> Deprecation free 5.1 security config

- symfony/framework-bundle/5.1/config/packages
- symfony/framework-bundle/5.1/config/packages/cache.yaml
- symfony/framework-bundle/5.1/config/packages/framework.yaml
- symfony/framework-bundle/5.1/config/packages/test
The `APP_SECRET` is defined but never set to the framework configuration.
> Add secret env to framework configuration

- symfony/framework-bundle/5.1/src/Kernel.php
| Doc issue/PR  | not needed yet - will finish maker
This cherry-picks part of #765. We're working on a command to convert yml service files to php files over at symfony/maker-bundle#604. For this to work, the user's kernel needs to at least *allow* for PHP service files to be read.
> Allowing php config in the kernel

- doctrine/doctrine-migrations-bundle/1.2/config/packages/doctrine_migrations.yaml
- doctrine/doctrine-migrations-bundle/1.2/manifest.json
Is there anything that prevents doing so, if the book can be fixed?
Replaces #796
> Move src/Migrations/ to migrations/

- symfony/framework-bundle/4.2/config/services.yaml
IMHO, this notation is easier to understand. More over it scales really
better. Finally this notation is not documented on the [following
page](https://symfony.com/doc/current/service_container.html)
> [FrameworkBundle] Use an array for exclude directive

- symfony/mobyt-notifier/5.2/manifest.json
| Doc issue/PR  | symfony/symfony-docs#13606 / symfony/symfony#36648
> Add Mobyt Notifier recipe

- phpunit/phpunit/4.7/post-install.txt
| Doc issue/PR  | not needed
The previous message appears to some people like Symfony is trying to "force" people what to do or to replace PHPUnit. 
In reality, the goal is to make sure the user is aware that - to follow the "documented path" - the bridge is available. But if they still want to install PHPUnit, that's totally fine.
Related to: https://github.com/symfony/symfony/issues/27289 and https://twitter.com/Ocramius/status/1293169839582973952
> Tweaking phpunit post-install message to give more information/context

- doctrine/doctrine-fixtures-bundle/3.0/src/DataFixtures/AppFixtures.php
I just noticed that the recipe is pointing to the old namespace of the `ObjectManager` class
> [DoctrineFixturesBundle] Update ObjectManager old namespace

- symfony/requirements-checker/2.0/manifest.json
The public/check.php file was removed in requirements-checker 2.0.
> Add recipe for symfony/requirements-checker 2.0

- symfony/sendinblue-mailer/5.2/manifest.json
- symfony/sendinblue-mailer/5.3/manifest.json
| Doc issue/PR  | [https://github.com/symfony/symfony-docs/pull/14272](https://github.com/symfony/symfony-docs/pull/14272)
> [Mailer] Added Sendinblue bridge recipe

- symfony/framework-bundle/4.2/manifest.json
- symfony/framework-bundle/4.4/config/preload.php
- symfony/framework-bundle/5.1/config/preload.php
- symfony/framework-bundle/5.2/manifest.json
Follows https://github.com/symfony/symfony/issues/38334
> [symfony/framework-bundle] Add config/preload.php

- easycorp/easyadmin-bundle/3.0/manifest.json
As discussed in #827 EA3 doesn't need a recipe, but EA2 defined one, so we need to create an empty recipe to nullify the existing one.
> Added an empty recipe for EA3

- symfony/framework-bundle/3.3/public/index.php
- symfony/framework-bundle/4.2/public/index.php
- symfony/framework-bundle/4.4/public/index.php
- symfony/framework-bundle/5.1/public/index.php
| Doc issue/PR  | https://github.com/symfony/symfony/pull/38954
> [FrameworkBundle] Replace deprecated Request::HEADER_X_FORWARDED_ALL constant

- doctrine/doctrine-bundle/1.6/manifest.json
- doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml
Requires https://github.com/dunglas/symfony-docker-skeleton/pull/5 and https://github.com/symfony/flex/pull/128.
> [doctrine-bundle] Docker support

- doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/1.6/manifest.json
| Doc issue/PR  | (Wouter is already checking into some related changes from #113)
This changes the `.env` to this:
```
###> doctrine/doctrine-bundle ###
#
DATABASE_URL="postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8"
###< doctrine/doctrine-bundle ###
```
> listing mysql, pgsql and sqlite DATABASE_URL examples in .env

- symfony/mercure-bundle/0.1/manifest.json
| Doc issue/PR  | todo
Mercure is now available as a Caddy server module, which is shipped by default by Symfony Docker (https://github.com/dunglas/symfony-docker/pull/89), and will be soon in API Platform.
This service isn't necessary anymore.
> [symfony/mercure-bundle] remove the Docker Compose service

- symfony/webpack-encore-bundle/1.0/package.json
- symfony/webpack-encore-bundle/1.6/config/packages/webpack_encore.yaml
To merge when the UX packages and the bridge are released with Stimulus 2 support
> Migrate Webpack Encore recipe to Stimulus 2

- nelmio/cors-bundle/1.5/manifest.json
- Wrap value between simple quotes: avoid shell error when sourcing `.env` file
Fixes symfony/recipes#848
> [nelmio/cors-bundle] Fix CORS_ALLOW_ORIGIN format

- friendsofphp/php-cs-fixer/2.16/.php_cs.dist
- friendsofphp/php-cs-fixer/2.16/manifest.json
| Doc issue/PR  | none
Since version 2.16.0, `@Symfony` ruleset is including `array_syntax` option. So, such option is not needed any more.
> remove "array_syntax" option in php-cs-fixer configuration

- symfony/allmysms-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14739
> Add recipe for AllMySms Notifier bridge

- symfony/webpack-encore-bundle/1.0/package.json
Webpack Encore 1.0 was just released 🌟 
PR #883 is now just for the upcoming stimulus-bridge release.
> bumping to encore 1.0

- symfony/webpack-encore-bundle/1.0/webpack.config.js
| Doc issue/PR  | WIP - I'm reviewing all the Encore docs currently
I originally (4 years ago) used `var` because `const` were still relatively new and not necessarily known widely. I think that's not true anymore, so let's use the more modern `const.
Cheers!
> switching var to const to be more modern

- symfony/webpack-encore-bundle/1.0/assets/bootstrap.js
- symfony/webpack-encore-bundle/1.0/package.json
| Doc issue/PR  | It appears nothing is needed
This is waiting on:
This affects all version of WebpackEncoreBundle... but it's an odd case where the bundle and Webpack encore itself are not very "bound" together. We could update this recipe in only the latest WebpackEncoreBundle version... or even bump a new minor version of the bundle and add it there. This relates to https://github.com/symfony/recipes#updating-recipes
> Updating package.json and bootstrap.js for upcoming stimulus-bridge

- symfony/panther/1.0/manifest.json
Companion PR of symfony/panther#399: automatically adds Chrome and ChromeDriver in the Docker image when installing Panther.
> [panther] add Chrome and ChromeDriver to the Dockerfile

- symfony/webpack-encore-bundle/1.0/manifest.json
Currently, it's not obvious how to start using Symfony DX. Actually the "entrypoint" of Symfony UX is Webpack Encore. I suggest adding a new alias to Encore to provide an easy step to get started with Symfony UX: `composer req ux`.
Companion PR of #890.
> Register a new "ux" alias

- doctrine/doctrine-bundle/2.0/post-install.txt
doctrine/doctrine-bundle/2.0/post-install.txt was not changed for postgresql in https://github.com/symfony/recipes/pull/113/commits/6a91adfe6230f753d0175bcdbdba6e0f673acdd2. This PR unlinks previous https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/post-install.txt and provides updated messages
> [doctrine/doctrine-bundle/2.0] Update post-install.txt for postgresql

- symfony/framework-bundle/5.3/config/packages/cache.yaml
- symfony/framework-bundle/5.3/config/packages/framework.yaml
- symfony/framework-bundle/5.3/config/packages/test/framework.yaml
- symfony/framework-bundle/5.3/config/preload.php
- symfony/framework-bundle/5.3/config/routes/dev/framework.yaml
- symfony/framework-bundle/5.3/config/services.yaml
- symfony/framework-bundle/5.3/manifest.json
- symfony/framework-bundle/5.3/post-install.txt
- symfony/framework-bundle/5.3/public/index.php
- symfony/framework-bundle/5.3/src/Kernel.php
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14939
When this is turned on (the default) one can hit a route that accepts only PUT, but with a POST.
Shouldn't we disable this by default, as it's not that commonly needed, isn't it?
> Disable "http_method_override" by default

- symfony/framework-bundle/5.3/config/packages/test/framework.yaml
| Doc issue/PR  | https://github.com/symfony/symfony/issues/40282
Get the session storage mock file from the storage factory. Possible solution for #40282
> get mock storage from the factory

- zenstruck/foundry/1.9/config/packages/dev/zenstruck_foundry.yaml
- zenstruck/foundry/1.9/config/packages/test/zenstruck_foundry.yaml
- zenstruck/foundry/1.9/manifest.json
- zenstruck/foundry/1.9/post-install.txt
| Doc issue/PR  | symfony/symfony-docs#14731
Based on slack discussions with @weaverryan & @wouterj.
Foundry has the concept of [auto-refreshing entities](https://github.com/zenstruck/foundry#auto-refresh) - prior to 1.9, this was disabled by default as there are caveats (entity changes silently lost). In 1.9, the caveats still exist but we were [able to throw a helpful exception](https://github.com/zenstruck/foundry/pull/131). We would now like auto-refreshing entities enabled by default but this would be a BC break in 1.x. A recipe to enable in 1.x was decided as the next best thing.
The double config is unfortunate but we couldn't think of a better way.
Likely we'll want a `post-install.txt` and probably some config …
> Add zenstruck/foundry

- symfony/monolog-bundle/3.7/config/packages/dev/monolog.yaml
- symfony/monolog-bundle/3.7/config/packages/prod/deprecations.yaml
- symfony/monolog-bundle/3.7/config/packages/prod/monolog.yaml
- symfony/monolog-bundle/3.7/config/packages/test
- symfony/monolog-bundle/3.7/manifest.json
| Doc issue/PR  | todo
Follows https://symfony.com/blog/logging-in-symfony-and-the-cloud and https://github.com/api-platform/api-platform/pull/1805.
Logging on `stderr` is considered a best practice in most containerized environments including SymfonyCloud, Docker and Kubernetes. It looks like the best default for new projects.
This PR also changes the default format used in production to JSON to improve the compatibility with modern logging systems such as ELK, EFK or DataDog (and even when using the command-line thanks to `jq`).
I targeted MonologBundle 3.7 to not impact existing installations.
> monolog: log on stderr and use JSON in prod

- friendsofphp/php-cs-fixer/2.17/.php_cs.dist
- friendsofphp/php-cs-fixer/2.17/manifest.json
Follows FriendsOfPHP/PHP-CS-Fixer#4828
> CS Fixer: Don't use the deprecated create method

- symfony/console/5.3/bin/console
- symfony/console/5.3/manifest.json
- symfony/framework-bundle/5.3/public/index.php
This recipe-update is a sidekick of https://github.com/symfony/symfony/pull/36652
As you can see, much of the logic has been removed from the recipe and moved to vendor/. This means it will be easier to upgrade such apps.
> Leverage the new Runtime component

- doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.3/config/packages/prod/doctrine.yaml
- doctrine/doctrine-bundle/2.3/config/packages/test/doctrine.yaml
- doctrine/doctrine-bundle/2.3/manifest.json
- doctrine/doctrine-bundle/2.3/post-install.txt
| Doc issue/PR  | https://github.com/doctrine/DoctrineBundle/pull/1290    
Depends on:
1290 proposes to add a new `doctrine.dbal.override_url` param that will allow you to override parts of a `DATABASE_URL`.
> add support for override_url

- symfony/framework-bundle/5.3/config/services.yaml
These lines are hard to explain and understand, and they cover advanced use cases.
Let's keep things simple.
Also, this use case should be better covered by https://github.com/symfony/symfony/pull/40555 in the future.
> [symfony/framework-bundle/5.3] remove "controller.service_arguments"

- symfony/mercure-bundle/0.3/config/packages/mercure.yaml
- symfony/mercure-bundle/0.3/manifest.json
| Doc issue/PR  | todo
Add support for MercureBundle 0.3 (to be tagged soon). This change allows using for publication and subscription. This especially useful in production and when using Docker, so you send requests to the hub using the network from PHP (like `http://hub/.well-known/mercure`, but subscribe using a public from the JS code (`https://hub.example.com/.well-known/mercure`).
See also https://github.com/symfony/recipes/pull/917.
cc @azjezz
> MercureBundle: add support for v0.3

- symfony/framework-bundle/5.3/config/packages/framework.yaml
| Doc issue/PR  |  -
This fixes the following notice on symfony/framework-bundle:5.3-dev
> Since symfony/framework-bundle 5.3: Not setting the "framework.session.storage_factory_id" configuration option is deprecated, it will default to "session.storage.factory.native" and will replace the "framework.session.storage_id" configuration option in version 6.0.
/cc @jderusse
> Fix deprecation in 5.3' session config

- doctrine/doctrine-migrations-bundle/3.1/config/packages/doctrine_migrations.yaml
- doctrine/doctrine-migrations-bundle/3.1/manifest.json
| Related  | https://github.com/doctrine/DoctrineMigrationsBundle/pull/407    
~Will be updated after release of doctrine migrations 3.1~
Release: https://github.com/doctrine/DoctrineMigrationsBundle/releases/tag/3.1.0
> [Doctrine Migrations] Enable new profiler by default in development

- symfony/microsoft-teams-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/15193
> [Notifier] Add Microsoft Teams

- doctrine/doctrine-bundle/2.3/config/packages/test/doctrine.yaml
Unrecognized option "username" under "doctrine.dbal.connections.default"
> Wrong comment in doctrine/doctrine-bundle 2.3 recipe

- symfony/monolog-bundle/3.7/config/packages/dev/monolog.yaml
This PR partially reverts a change done in #894: logging on stderr by default in the dev env breaks the DX, because the output of console commands becomes a mess, with log line mangling the command's output.
> Log in var/log in dev

- friendsofphp/php-cs-fixer/2.19/.php-cs-fixer.dist.php
- friendsofphp/php-cs-fixer/2.19/manifest.json
- friendsofphp/php-cs-fixer/3.0/.php-cs-fixer.dist.php
- friendsofphp/php-cs-fixer/3.0/manifest.json
Following https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.19.0
More specific:
[minor #5607 DX: new config filename (keradus)](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5607)
cc @keradus
> Update recipe for PHP-CS-Fixer 2.19.0 and 3.0.0

- symfony/security-bundle/5.3/config/packages/security.yaml
- symfony/security-bundle/5.3/manifest.json
| Doc issue/PR  | I'm working on it :wink: 
As of 5.3, the authenticator security is no longer experimental (ref: https://github.com/symfony/symfony/pull/40814 ). We're going to revamp the security docs for 5.3 to always use the authenticator security. I think it's good to also default to this new system in 5.3.
```diff
--- symfony/security-bundle/5.1/config/packages/security.yaml
+++ symfony/security-bundle/5.3/config/packages/security.yaml
@@ -1,4 +1,6 @@
security:
+    # https://symfony.com/doc/current/security/experimental_authenticators.html
+    enable_authenticator_manager: true
providers:
users_in_memory: { memory: null }
@@ -7,7 +9,6 @@
pattern: ^/(_(profiler|wdt)|css|images|js)/
security: false
main:
- …
```
> [symfony/security-bundle:5.3] Enable authenticator security by default

- symfony/framework-bundle/5.3/src/Kernel.php
Spotted while reviewing https://github.com/symfony/symfony/pull/41218
Using `->withPath()` allowed passing the `Kernel` to the closure, but since 5.3, this is not needed anymore since the `$env` var is now available. This also fixes using config builders inside `services.php`.
> [framework-bundle/5.3] fix importing services/routes.php

- symfony/framework-bundle/4.4/manifest.json
- symfony/framework-bundle/5.1/manifest.json
- symfony/framework-bundle/5.2/manifest.json
- symfony/framework-bundle/5.3/manifest.json
To me every private key should be excluded by default independent of the environment.
Esp. if you use other deployment environments like staging, having this unsecure default as gitignore is kinda dangerous.
The fact that custom env don't have the private key ignored by default and https://symfony.com/doc/current/configuration.html#creating-a-new-environment does not mention it that this should be done manually is a potential security problem.
If the secrets from dev or test are not really secrets (which is why you could commit the private key), then there is not point in setting them as secrets in the first place. Those can just be normal env vars.
For the test env this is already recommended in …
> Also ignore secret private key by default for non-prod environments

- symfony/framework-bundle/5.4/config/packages/cache.yaml
- symfony/framework-bundle/5.4/config/packages/framework.yaml
- symfony/framework-bundle/5.4/config/preload.php
- symfony/framework-bundle/5.4/config/routes/framework.yaml
- symfony/framework-bundle/5.4/config/services.yaml
- symfony/framework-bundle/5.4/manifest.json
- symfony/framework-bundle/5.4/post-install.txt
- symfony/framework-bundle/5.4/public/index.php
- symfony/framework-bundle/5.4/src/Kernel.php
This PR changes the Kernel for two reasons:
* consistency
* using relative paths breaks when extending the Kernel
I was doing the latter for testing purposes (I want to import some configurations only in certain tests, not in all the `test` environment) and it breaks under this situation.
If this gets merged, maybe we could consider backporting it to older recipes too?
> Remove usages of relative paths from Kernel

- symfony/webpack-encore-bundle/1.9/config/packages/webpack_encore.yaml
| Doc issue/PR  | TODO
This should be... just this simple! We should have a `data-turbo-track` on our `script` and `link` tags. The result is that, when the versioned filename changes, the full page will refresh.
Ref: https://turbo.hotwire.dev/handbook/drive#reloading-when-assets-change
Thanks!
> Suggest data-turbo-track="reload" attribute for Turbo users in Encore

- symfony/security-bundle/5.3/config/packages/security.yaml
This PR configures a default "auto" password hasher on 5.3.
If one creates a user class implementing `PasswordAuthenticatedUserInterface` (i.e. authenticated via password), then one just has to use the password-hashing related services that are wired from this config. 
In case these services are not used anywhere, they are just removed from the container as usual.
Fixes https://github.com/symfony/symfony/issues/42071
> [security-bundle/5.3] Configure `auto` password hasher

- scheb/2fa-bundle/5.0/config/packages/scheb_2fa.yaml
- scheb/2fa-bundle/5.0/config/routes/scheb_2fa.yaml
- scheb/2fa-bundle/5.0/manifest.json
I propose to move @scheb's 2fa bundle from the contrib repository to the official recipes:
- This bundle provides multi factor authentication, a feature which we likely won't ever cover fully in Symfony core and rather rely on this bundle.
- The bundle is stable, works great and @scheb is doing a great job of keeping up to date with Symfony versions (and even giving feedback on new security changes that affect the bundle).
For discoverability, I also propose to give the bundle the "2fa" alias.
> Add scheb/2fa-bundle to official recipes

- symfony/mailer/4.3/manifest.json
When using the Mailer locally, let's use a mail catcher automatically.
/cc @dunglas 
> Add local Docker config for Mailer

- api-platform/admin-pack/1.0/post-install.txt
- api-platform/core/2.1/post-install.txt
- api-platform/core/2.5/post-install.txt
- doctrine/doctrine-bundle/1.12/post-install.txt
- doctrine/doctrine-bundle/1.6/post-install.txt
- doctrine/doctrine-bundle/2.0/post-install.txt
- doctrine/doctrine-bundle/2.3/post-install.txt
- doctrine/doctrine-bundle/2.4/post-install.txt
- hautelook/alice-bundle/2.1/post-install.txt
- symfony/framework-bundle/3.3/post-install.txt
- symfony/framework-bundle/3.4/post-install.txt
- symfony/framework-bundle/4.2/post-install.txt
- symfony/framework-bundle/4.4/post-install.txt
- symfony/framework-bundle/5.1/post-install.txt
- symfony/framework-bundle/5.2/post-install.txt
- symfony/framework-bundle/5.3/post-install.txt
- symfony/framework-bundle/5.4/post-install.txt
- symfony/mailer/4.3/post-install.txt
- symfony/messenger/4.1/post-install.txt
- symfony/messenger/4.3/post-install.txt
- symfony/panther/1.0/post-install.txt
- symfony/phpunit-bridge/3.3/post-install.txt
- symfony/phpunit-bridge/4.1/post-install.txt
- symfony/phpunit-bridge/4.3/post-install.txt
- symfony/phpunit-bridge/5.1/post-install.txt
- symfony/phpunit-bridge/5.3/post-install.txt
- symfony/webpack-encore-bundle/1.9/post-install.txt
- zenstruck/foundry/1.9/post-install.txt
When installing a pack or when installing multiple packages at once, you might have a confusing output at the end of the `composer` run as many post install file might be displayed as most of the start with a blue "What's next" header.
In a Flex PR, I will propose to move the header to Flex and Flex will also add a small header between each post install to associate each post install file to its package. See https://github.com/symfony/flex/pull/790
I'm opening this PR so that I can test things and see how I can improve the output by making some experiments.
So, please NO MERGE.
> Remove the header from post-install files (handled by Flex soon)

- symfony/webpack-encore-pack/1.0/manifest.json
- symfony/webpack-encore-pack/1.0/post-install.txt
The pack was deprecated years ago and the package does not exist anymore.
> Remove webpack encore pack recipe

- doctrine/doctrine-bundle/2.3/config/packages/prod/doctrine.yaml
- doctrine/doctrine-bundle/2.4/config/packages/prod/doctrine.yaml
Removed deprecated configuration key metadata_cache_driver from DoctrineBundle config for 2.3 and 2.4, fixes #994
> [DoctrineBundle] Removed deprecated config

- blackfireio/blackfire-symfony-meta/1.0/.blackfire.yaml
- blackfireio/blackfire-symfony-meta/1.0/manifest.json
- blackfireio/blackfire-symfony-meta/1.0/post-install.txt
> Add a recipe to ease installation of Blackfire

- symfony/security-bundle/5.3/config/packages/security.yaml
Authenticator manager doc url is changed, see https://github.com/symfony/symfony-docs/pull/15405
> Change authenticator manager doc url

- symfony/routing/6.0/config/packages/routing.yaml
- symfony/routing/6.0/config/routes.yaml
- symfony/routing/6.0/manifest.json
Currently, installing `doctrine/annotations` is needed to be able to use the `#[Route()]` PHP 8 attribute. It'unfortunate because attributes can work out of the box and this dependency is not needed with PHP 8.
This PR enables "annotation" support (actually attribute support) by default, even if `doctrine/annotations` isn't installed.
This PR targets Symfony 5.3 as it's a new feature. A side effect will be that the default skeleton will not work by default with PHP 7, but IMHO it's not a big issue because most new projects using Symfony 5.3 should use PHP 8. Also, this moves the ecosystem forward.
> Routing: don't require to install doctrine/annotations to use attributes

- symfony/twig-bundle/5.4/templates/base.html.twig
This adds an inlined/embedded favicon to avoid 404 errors when browsers try to get it.
We can change the emoji character if you like. E.g. the black circle --> ⚫️  could resemble the Symfony logo?
> Add an embedded favicon to the base template

- symfony/webpack-encore-bundle/1.9/assets/controllers/hello_controller.js
- symfony/webpack-encore-bundle/1.9/package.json
| Doc issue/PR  | Unfortunately, not needed because ALL of this stuff still needs to be documented (on my list). The symfony/ux package documentation has been updated
This is waiting on new major tags from `@symfony/stimulus-bridge` (v3) and `symfony/ux` (v2).
I have no modified the recipe for earlier versions of Encore. I believe that is more consistent with our policy of not changing recipes for old versions.
Cheers!
> Updating recipe for Stimulus 3

- .github/workflows/callable-flex-update.yml
| Doc issue/PR  | TODO (mentioned on the main PR)
See https://github.com/symfony/flex/pull/845
Once https://github.com/symfony-tools/recipes-checker/pull/2 is merged, this can be merged.
> Copying the "archived/" directory from recipes-checker

- zenstruck/foundry/1.9/config/packages/dev/zenstruck_foundry.yaml
- zenstruck/foundry/1.9/post-install.txt
Hi, just a few doc links update as docs have moved to Symfony.com docs.
> Fix zenstruck/foundry doc links

- symfony/security-bundle/5.3/config/packages/security.yaml
| Doc issue/PR  | Fix #1024
Perhaps we could create a [`test-hasher`](https://github.com/symfony/recipes/issues/1024#issuecomment-975504242) in Symfony itself but this wouldn't be available until 6.1. Until then, I believe this is an easy win.
This is documented in the [4.4 docs](https://symfony.com/doc/4.4/testing/http_authentication.html) but was lost (I think) after a documentation refactor.
My argument for not using `plaintext` [is here](https://github.com/symfony/recipes/issues/1024#issuecomment-975015039) but I'm not strongly opposed to it.
> [symfony/security-bundle] use lowest possible p/w hash "work factor" in test env

- .github/workflows/callable-flex-update-archived.yml
- .github/workflows/flex-update-archived.yml
| Doc issue/PR  | None
Relates to: https://github.com/symfony-tools/recipes-checker/pull/3
On push to `main` - which is rare - we would run the new command to completely repopulate the `archived` directory on the `flex/main` branch. This really only needs to be done once, because it's kept up to date after automatically. But we could choose to run it on push just in case.
There IS one problem: how to replicate this for `recipes-contrib`?
> Add callable action to repopulate the recipe archives

- .github/workflows/flex-update-achived.yml
| Doc issue/PR  | Relates to #1038 
This will allow us to manually trigger this new GH action to build the `archived/` directory.
> Adding manual action for flex-update-archived

- doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
Needs https://github.com/symfony/symfony/pull/42054 to be released before merging.
> Rely on defaults for doctrine mapping types

- symfony/webpack-encore-bundle/1.9/post-install.txt
| Doc issue/PR  | Working on updating docs now...
If you have TwigBundle 5.4, then the helpers are already uncommented. But since we don't know what version of TwigBundle the user has, I think, for now, this is the best middleground.
Cheers!
> Tweaking "post install" message: Encore functions may already be uncommented

- scheb/2fa-bundle/5.0/config/packages/scheb_2fa.yaml
- scheb/2fa-bundle/6.0/config/packages/scheb_2fa.yaml
- scheb/2fa-bundle/6.0/config/routes/scheb_2fa.yaml
- scheb/2fa-bundle/6.0/manifest.json
- Add up-to-date recipe files for `scheb/2fa-bundle` version 6
- Fix the documentation URL on v5
> Recipe files for scheb/2fa-bundle v6

- scheb/2fa-bundle/5.0/config/routes/scheb_2fa.yaml
- scheb/2fa-bundle/6.0/config/routes/scheb_2fa.yaml
The controller syntax needs to be different for Symfony 6
> Update controller syntax in scheb/2fa-bundle

- symfony/framework-bundle/4.2/config/services.yaml
- symfony/framework-bundle/4.4/config/services.yaml
- symfony/framework-bundle/5.1/config/services.yaml
- symfony/framework-bundle/5.2/config/services.yaml
- symfony/framework-bundle/5.3/config/services.yaml
- symfony/framework-bundle/5.4/config/services.yaml
Since Symfony 4 & Flex the default directory structure doesn't have a `src/Tests` folder making the exclude redundant.
> [FrameworkBundle] Remove src/Tests from list of excluded folders

- .github/workflows/callable-qa.yml
This PR provides an integration with changes from https://github.com/symfony-tools/recipes-checker/pull/1
> Specify license for recipes-checker-main lint:pull-request

- doctrine/doctrine-bundle/2.3/manifest.json
- doctrine/doctrine-bundle/2.4/manifest.json
| Doc PR  | https://github.com/symfony/symfony-docs/pull/16515
Because of backward-compatibility reasons, not specifying the charset
will result in "utf8" being used, which is a deprecated charset.
Also, when the charset for creating tables is not specified, the one
specified in the DSN is reused if specified.
In the future, DBAL is going to drop default values, which means we will
have to specify a charset anyway.
See:
- https://github.com/doctrine/dbal/pull/5277 (about the reuse of connection charset for table charset)
- https://github.com/doctrine/dbal/pull/4644
> Specify charset when using MySQL

- doctrine/annotations/1.10/manifest.json
> Skip recipe for doctrine/annotations when symfony/routing 6 is installed

- .github/workflows/callable-recipe-readme-update.yml
| Doc issue/PR  | None
Relates to https://github.com/symfony-tools/recipes-checker/pull/9. That should be merged first, then I can test this on a fork.
> Adding a new callable recipes readme GH action

- .github/workflows/callable-recipe-readme-update.yml
- .github/workflows/flex-update.yml
- README.rst
See: https://github.com/symfony/recipes/pull/1079#issuecomment-1114031628
This changes the `RECIPES.md` to live on the flex/main branch... which is fine. We we link to it, it's mostly there as a resource IF you need it.
Tested over on my fork (though, that wasn't enough last time due to permission differences in the settings between the branches).
RELATED
* update recipes-checker to update URL to the RECIPES.md: https://github.com/symfony-tools/recipes-checker/pull/10
* Update contrib to not pass the branch arg: https://github.com/symfony/recipes-contrib/pull/1402
> Switching recipes readme to be on flex-main branch

- symfony/ux-autocomplete/2.2/config/routes/ux_autocomplete.yaml
- symfony/ux-autocomplete/2.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/ux/pull/330
Hi!
This adds a recipe for the proposed new ux-autocomplete package... the only needed thing is the route import.
Cheers!
> [symfony/ux-autocomplete] Adding UX autocomplete recipe

- symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml
Reverts symfony/recipes#1087
Not needed since https://github.com/symfony/webapp-pack/pull/7
> Revert "[webpack-encore-bundle] disable strict_mode by default"

- symfony/webpack-encore-bundle/1.10/package.json
Encore 3 is out: https://github.com/symfony/webpack-encore/releases/tag/v3.0.0
The other version bumps aren't necessary and we don't need to keep them up to date. Still, it seems prudent to occasionally bump them to a version closer to the latest.
Cheers!
> bumping encore to v3 and increasing some other dependencies

- symfony/framework-bundle/6.2/config/services.yaml
I always must google if it is `services.bind`, `services._bind` or `services._defaults.bind` or even `services._defaults._bind`. Think it would be great to have this example in it.
> Add example how to bind arguments to the services.yaml

- doctrine/doctrine-migrations-bundle/3.1/config/packages/doctrine_migrations.yaml
| Doc issue/PR  | https://github.com/symfony/symfony/issues/47275
imho we should not activate this by default, but rather let ppl discover this feature as [documented here](https://github.com/doctrine/DoctrineMigrationsBundle/pull/471)
> Doctrine Migration profiler disabled by default

- symfony/webpack-encore-bundle/1.10/webpack.config.js
Now that the minimum version for core-js has been bumped to 3.23 in package.json, it should be bumped in the @babel/preset-env configuration also.
The reason for this is explained well here: https://babeljs.io/docs/en/babel-preset-env#corejs
> It is recommended to specify the minor version otherwise "3" will be interpreted as "3.0" which may not include polyfills for the latest features.
This means polyfills released between > 3.0 and <= 3.23 are not being included during builds with the current default configuration.
> [symfony/webpack-encore-bundle] Update babel preset-env config to use corejs 3.23

- symfony/webpack-encore-bundle/1.10/webpack.config.js
"Subdirectory" is correctly spelled as one word.
> Fix small typo in symfony/webpack-encore-bundle

- league/oauth2-server-bundle/0.4/manifest.json
> [league/oauth2-server-bundle] Add aliases 

- symfony/lock/4.4/manifest.json
- symfony/lock/5.2/manifest.json
`semaphore` is not always installed in any system. So it would be better to have a default which works everywhere
> use flock in default as it works out of the box

- symfony/framework-bundle/6.2/config/packages/uid.yaml
Symfony 6.2 introduces support for UUID v7, which is to be preferred over UUID v6 [according to the draft RFC][1]:
> Implementations SHOULD utilize UUID version 7 over UUID version 1 and
> 6 if possible.
In order not to change the UUID generation in existing projects, UUID v7 could be configured as default for new projects via this recipe.
[1]: https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#section-5.2-2
> Use UUID v7 as default for new projects

- symfony/framework-bundle/6.2/config/services.yaml
Reverting #1119
In 6.2, people are going to use `#[Autowire]` most of the time instead IMHO.
> Revert "Add example how to bind arguments to the services.yaml (#1119)"

- .github/versions.json
- symfony/bandwidth-notifier/6.3/manifest.json
| Doc issue/PR  | [symfony/symfony-docs#...](https://github.com/symfony/symfony-docs/pull/17483)
> [Notifier] Add Bandwidth bridge

- symfony/line-notify-notifier/6.3/manifest.json
| PR  | https://github.com/symfony/symfony/pull/48466
| Doc issue | https://github.com/symfony/symfony-docs/pull/17500
> [Notifier] Add LINE Notify notifier

- doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
When auto_generate_proxy_classes: false is set, the proxies need to be pre-generated with the cache warmer. So in this case, the files are much better suited in the build dir. The build dir is the same as the cache dir by default. But for people trying to use the build dir properly, this makes much more sense. See https://github.com/symfony/symfony/issues/40827#issuecomment-820653578
> Put doctrine proxies in build dir for production

- symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml
The cache option is explained twice, feels like the one under `webpack_encore` https://github.com/symfony/recipes/blob/923757ec093b9b7831891af0462bd5dfb031f020/symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml#L33-L35 was left over still showing the old config.
But the same thing is written down at the new `when@prod` https://github.com/symfony/recipes/blob/923757ec093b9b7831891af0462bd5dfb031f020/symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml#L43-L45.
> [encore] Removed duplicate cache config comment

- symfony/mailer/4.3/manifest.json
Follow Docker's string recommendations for port mappings: https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
> [symfony/mailer] follow string recommendations

- symfony/phpunit-bridge/3.3/tests/bootstrap.php
- symfony/phpunit-bridge/4.1/tests/bootstrap.php
- symfony/phpunit-bridge/4.3/tests/bootstrap.php
- symfony/phpunit-bridge/5.1/tests/bootstrap.php
- symfony/phpunit-bridge/5.3/tests/bootstrap.php
When running functional tests with an empty cache (no directory), the cache directory is created. I run my tests with `APP_DEBUG=1`. I expect the cache directory to be created with the same permissions whether it is created from the tests or from a real request on the front controller. Currently, running the tests and then accessing the application lead to unexpected permissions errors.
Ref https://github.com/symfony/recipes/pull/210
> symfony/phpunit-bridge: set umask(0000) when debug is true

- doctrine/doctrine-bundle/2.8/manifest.json
Based on hadolint docker, adding quotes to `$(nproc)` to prevent word splitting.
> fix(doctrine): adding quote to prevent word splitting in Dockerfile

- symfony/simple-textin-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17510
> [Notifier] Add SimpleTextin bridge

- doctrine/doctrine-bundle/2.8/manifest.json
I did see in the past a lot of misconfigured versions strings for users which did use @sulu with `mariadb` and run into an SQL error because they did not configure the mariadb version string instead used mysql version. Think it would make sense to have also mariadb as an example beside mysql and sqlite.
Related PRs: https://github.com/doctrine/dbal/pull/5971
> Add mariadb example to DATABASE_URL

- nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml
Follows https://github.com/php-http/message-factory/pull/42 and https://github.com/Nyholm/psr7/pull/243
> Remove autowiring aliases for deprecated Httplug factories

- symfony/ux-translator/2.7/manifest.json
The class TranslatorBundle of the Symfony UX Translator component has recently been renamed to UxTranslatorBundle (Commit [bc96739](https://github.com/symfony/ux-translator/commit/bc96739e03cc6312f7b49cab4cb7c7060c3e4999)).
Currenty, the following line added to the bundles.php file is as the following :
```Symfony\UX\Translator\TranslatorBundle::class => ['all' => true],```
It needs to be renamed here too so it won't lead to the following error after the install :
> [symfony/ux-translator] TranslatorBundle class now prefixed by Ux

- php-http/discovery/1.18/config/packages/http_discovery.yaml
- php-http/discovery/1.18/manifest.json
Note that php-http/discovery itself defaults to nyholm/psr7 so in practice this shouldn't change much, except for people that want to rely on another PSR-17 implementation.
> Prefer php-http/discovery over nyholm/psr7 when installed

- symfony/stimulus-bundle/2.8/manifest.json
- symfony/stimulus-bundle/2.9/manifest.json
Hi!
This is one step in resolving https://github.com/symfony/ux/issues/907:
The StimulusBundle 2.9 recipe is set to conflict with
- (1) old Flex versions that don't support `add-lines` so that the recipe doesn't run and skip these important items
- (2) WebpackEncoreBundle 1.0 whose recipe adds many of the same files - StimulusBundle's recipe is meant to fit in with EncoreBundel 2.0's recipe.
I assumed that if no compatible recipe was found, Flex would still "auto-generate" a recipe and install the bundle. That actually does NOT happen.
This PR adds a "fake" StimulusBundle 2.8 recipe. That bundle doesn't exist in 2.8, but it installs just fine. The result is:
A) If you have WebpackEncoreBundle 2.0 …
> Add "early" StimulusBundle recipe without conflicts to ensure bundle is registered

- phpunit/phpunit/4.7/phpunit.xml.dist
- phpunit/phpunit/9.3/phpunit.xml.dist
- symfony/panther/1.0/manifest.json
- symfony/panther/1.0/post-install.txt
- symfony/phpunit-bridge/5.1/phpunit.xml.dist
- symfony/phpunit-bridge/5.3/phpunit.xml.dist
Leveraging https://github.com/symfony/flex/pull/975
> [symfony/panther] leverage the new add-lines configurator

- README.rst
The configurator has been added, but the list has not been updated : c101117
> [Doc] Add missing "container" configurator in the list

- symfony/framework-bundle/7.0/config/packages/framework.yaml
| Doc issue/PR  | Part of symfony/symfony#51097
`false` is the default setting since symfony/symfony#50873 (7.0)
> Remove http_method_override setting from recipe

- api-platform/admin-pack/1.0/post-install.txt
- symfony/webpack-encore-bundle/2.0/post-install.txt
> Recommend NPM instead of Yarn

- symfony/framework-bundle/6.4/config/packages/framework.yaml
- symfony/framework-bundle/7.0/config/packages/framework.yaml
This PR removes the `framework.session.storage_factory_id` option since it's already the default value.
> [FrameworkBundle] Remove "framework.session.storage_factory_id"

- symfony/phrase-translation-provider/6.3/manifest.json
- symfony/translation/6.3/config/packages/translation.yaml
- symfony/translation/6.3/manifest.json
| Doc PR  | symfony/symfony-docs#17861
| PR  | symfony/symfony#49231
> phrase translation provider recipe

- api-platform/core/2.1/post-install.txt
- api-platform/core/2.5/post-install.txt
- api-platform/core/3.0/post-install.txt
- api-platform/core/3.1/config/packages/api_platform.yaml
- api-platform/core/3.1/config/routes/api_platform.yaml
- api-platform/core/3.1/manifest.json
- api-platform/core/3.1/post-install.txt
Enabling the standard behavior for PUT requests is necessary to prevent a deprecation warning.
I also imported the defaults [we set in the API Platform distribution](https://github.com/api-platform/api-platform/blob/main/api/config/packages/api_platform.yaml).
> [api-platform/core] prevent a deprecation warning and sync with upstream

- api-platform/core/3.2/config/packages/api_platform.yaml
- api-platform/core/3.2/config/routes/api_platform.yaml
- api-platform/core/3.2/manifest.json
- api-platform/core/3.2/post-install.txt
In API Platform 4 `json` will be disabled by default so it's now recommended to explicit formats.
For `event_listeners_backward_compatibility_layer` see https://github.com/api-platform/core/pull/5657
We're using the Symfony Inflector now but this will probably break current code so we need a flag to `keep_legacy_inflector`
The `rfc_7807_compliant_errors` is to make Hydra errors compatible with the [JSON Problem](https://datatracker.ietf.org/doc/rfc7807/) specification. This may lead to unexpected error fields and therefore we need a compatibility flag.
> [api-platform/core] sane defaults for API Platform 3.2

- symfony/security-bundle/6.4/config/packages/security.yaml
- symfony/security-bundle/6.4/config/routes/security.yaml
- symfony/security-bundle/6.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/19000
Related to https://github.com/symfony/symfony/pull/50946
> [symfony/security-bundle] Leverage the `LogoutRouteLoader`

- symfony/ux-twig-component/2.13/config/packages/twig_component.yaml
- symfony/ux-twig-component/2.13/manifest.json
| Doc issue/PR  | https://github.com/symfony/ux/pull/1140
> Adding recipe for TwigComponent 2.13

- symfony/phpunit-bridge/5.3/bin/phpunit
- symfony/phpunit-bridge/6.3/bin/phpunit
Fixes #1248.
Our `bin/phpunit` calls the PHPUnit from the vendor folder, if we use Composer to install PHPUnit. Instead of calling `require` on PHPUnit's entrypoint directly, we call internal PHPUnit classes to bootstrap the CLI runner.
The reason for that was that PHPUnit's bin script contains a shebang (`#!/usr/bin/env php`) which would be output on PHP 7. On PHP 8 however, that limitation is gone and with it the reason for our workaround. Calling `require` on PHPUnit's entrypoint makes the bin/phpunit script more resilient against future internal changes in PHPUnit and allows the script to function with PHPUnit 10.
> Fix bin/phpunit for PHPUnit 10

- symfony/phpunit-bridge/6.3/phpunit.xml.dist
According to uncomment extensions block, we need to update the SYMFONY_PHPUNIT_VERSION variable to 9.6.
> Update SYMFONY_PHPUNIT_VERSION to 9.6

- symfony/asset-mapper/6.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/19252
If you want to have page-specific JS, you need to override `{{ importmap() }}` and NOT call it twice. If you override `javascripts` and do not call `parent()`, it could accidentally not include some other JS you have. So, the proposal is to wrap `{{ importmap() }}` in its own block so you can override it.
> [AssetMapper] surrounding importmap() in a block

- symfony/asset-mapper/6.4/importmap.php
- symfony/asset-mapper/6.4/manifest.json
| Doc issue/PR  | Not needed... people should now about `importmap:install`... but now they will likely never actually need to run it manually
From a suggestion by @stof - https://github.com/symfony/demo/pull/1449#issuecomment-1831722678 - it works really well!
> Asset mapper install as composer script

- doctrine/doctrine-bundle/2.10/manifest.json
| Doc issue/PR  | [Issue](https://github.com/symfony/recipes/issues/1266)
> [Doctrine Bundle][2.10] Dockerfile : Same command as 2.9

- symfony/asset-mapper/6.4/importmap.php
| Doc issue/PR  | None
It now exactly matches: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/ImportMap/ImportMapConfigReader.php#L130-L142
> import map -> importmap to match Symfony core generation

- symfony/unifonic-notifier/7.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/19300
Related to https://github.com/symfony/symfony/pull/53092
> Add notifier-unifonic

- symfony/bluesky-notifier/7.1/manifest.json
| Doc issue/PR  | tomorrow
Related to https://github.com/symfony/symfony/pull/53083
> Add bluesky notifier

- symfony/stimulus-bundle/2.13/assets/bootstrap.js
- symfony/stimulus-bundle/2.13/assets/controllers.json
- symfony/stimulus-bundle/2.13/assets/controllers/hello_controller.js
- symfony/stimulus-bundle/2.13/manifest.json
| Doc issue/PR  | StimulusBundle docs already updated
StimulusBundle + AssetMapper 6.4 no longer needs `ux_controller_link_tags()`. We can't target StimulusBundle's recipe based on the version of AssetMapper, but now that 6.4 is released, I think we should target recipe at the latest version.
> [StimulusBundle] Removing ux_controller_link_tags()

- symfony/sms-sluzba-notifier/6.4/manifest.json
| Doc issue/PR  | symfony/symfony-docs#19258
> [Notifier] Add recipe for sms-sluzba.cz bridge

- symfony/mailer/4.3/manifest.json
This PR replace the unmaintained `schickling` image with the official Mailcatcher image
> Update docker image for Mailcatcher

- symfony/asset-mapper/6.4/manifest.json
this is more to be consistent with the `/public/assets/` gitignore line above the fixed one; the set line is just fine
> [AssetMapper] gitignore `/assets/vendor/` as a directory

- symfony/crowdin-translation-provider/5.3/manifest.json
- symfony/loco-translation-provider/5.3/manifest.json
- symfony/phrase-translation-provider/6.3/manifest.json
- symfony/phrase-translation-provider/6.4/manifest.json
- symfony/translation/5.3/config/packages/translation.yaml
- symfony/translation/6.3/config/packages/translation.yaml
Mistake was done in https://github.com/symfony/recipes/pull/1217, fixed now.
In addition, I've added `add-lines` for Phrase Provider.
> [Translation] Fix translation provider add-lines instructions

- symfony/monolog-bundle/3.7/config/packages/monolog.yaml
The json formatter is configured for the main/nested handler in production; it should be set the same way for the deprecation handler to ensure uniformity.
> [monolog-bundle] set json formatter to deprecation handler

- symfony/framework-bundle/7.0/config/packages/framework.yaml
- symfony/routing/7.0/config/packages/routing.yaml
- symfony/routing/7.0/config/routes.yaml
- symfony/routing/7.0/manifest.json
- symfony/uid/7.0/manifest.json
- symfony/validator/7.0/config/packages/validator.yaml
- symfony/validator/7.0/manifest.json
> [framework-bundle] Remove options that match the defaults in 7.0

- symfony/twig-bundle/6.4/config/packages/twig.yaml
- symfony/twig-bundle/6.4/manifest.json
- symfony/twig-bundle/6.4/templates/base.html.twig
By default, Twig templates have the `.twig` extension. They can be collocated with other files (SVG, CSS, JS or even [PHP for Twig Components](https://twitter.com/weaverryan/status/1724827396279357498))
Adding the option `twig.file_name_pattern: '*.twig'` by default for new projects is necessary to avoid compiling non-twig files.
Related to symfony/symfony#45845
> Add TwigBundle 6.4 with `file_name_pattern: *.twig`

- symfony/phpunit-bridge/5.3/manifest.json
- symfony/phpunit-bridge/5.3/tests/bootstrap.php
- symfony/phpunit-bridge/6.3/manifest.json
- symfony/phpunit-bridge/6.3/tests/bootstrap.php
> Remove `config/bootstrap.php` when not needed anymore

- symfony/smsapi-notifier/5.2/manifest.json
> [Notifier] Fix value of option

- doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.10/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.8/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.9/config/packages/doctrine.yaml
> Enable `use_savepoints` by default for Doctrine DBAL

- symfony/asset-mapper/6.4/manifest.json
> Indent importmap block

- symfony/smsense-notifier/7.1/manifest.json
| Doc issue/PR  | [symfony/symfony-docs#...](https://github.com/symfony/symfony-docs/pull/19534)
> [Notifier][SMSense] Add recipe for SMSense notifier

- doctrine/doctrine-bundle/2.12/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.12/manifest.json
- doctrine/doctrine-bundle/2.12/post-install.txt
| Doc issue/PR  | https://github.com/doctrine/DoctrineBundle/pull/1762 & https://github.com/symfony/symfony-docs/pull/19671
Reflects the new default for doctrine.orm.controller_resolver.auto_mapping to ensure new users will not be faced with a deprecation when starting with doctrine bundle 2.12 or higher.
> [doctrine/doctrine-bundle] Disable controller resolver auto mapping by default

- symfony/webapp-pack/1.0/config/packages/messenger.yaml
Make bus configuration in `messenger.yaml` explicit to facilitate third-party bundles providing their bus configuration.
Without this configuration, if a bundle provides a bus configuration via a flex recipe, it silently becomes the default bus. Or if there is already a bus configuration, but without the `default_bus` setting, it will give us _"Invalid configuration for path "framework.messenger": You must specify the "default_bus" if you define more than one bus."_
> Explicit Messenger bus configuration

- symfony/console/5.3/bin/console
The error message `Symfony Runtime is missing. Try running "composer require symfony/runtime".` is missleading if no vendor directory exists. In that case somebody want to run a Symfony project just need to run `composer install`.
> Check for existence of vendor directory for better error message

- doctrine/doctrine-bundle/1.12/manifest.json
- doctrine/doctrine-bundle/1.6/manifest.json
- doctrine/doctrine-bundle/2.0/manifest.json
- doctrine/doctrine-bundle/2.3/manifest.json
- doctrine/doctrine-bundle/2.4/manifest.json
- doctrine/doctrine-bundle/2.8/manifest.json
- symfony/panther/1.0/manifest.json
Since the switch to Debian : https://github.com/dunglas/symfony-docker/pull/582
Fix : https://github.com/dunglas/symfony-docker/issues/587
> Switch dockerfile instruction to Debian

- doctrine/doctrine-bundle/2.12/config/packages/doctrine.yaml
Reverts the setting set in #1299
I'm not sure this is the solution we want to merge, but I'm sure the recent changes have not been made with DX in mind, and they're making the experience worse (see comments in https://github.com/symfony/recipes/pull/1299)
I'm kindly asking to redesign this change with DX in mind. :pray: If we don't have any better idea yet, I suggest reverting the change on DoctrineBundle until we have a DX-friendly solution.
> Enable entity automapping for controllers again

- symfony/panther/1.0/manifest.json
This change adds an apt update before the installation of the packages and clean up the /var/lib/apt/lists/ after. 
This will ensure that the package can be installed even if the previous docker layers using apt were cached and reduce the outputed layer size with unused apt cache files
> [symfony/panther] add apt update & clean during chromium driver install

- doctrine/doctrine-bundle/2.12/manifest.json
By default, root user is used to connect to the postgres database.
If the database does not have a "root" role, the following error is logged everytime the health check happens:
`FATAL:  role "root" does not exist`
It does not seem to affect the 'healthy' status of the container (the command still returns zero exit code), but it spams the log:
```
database-1  | 2024-04-18 06:26:08.016 UTC [67] FATAL:  role "root" does not exist
database-1  | 2024-04-18 06:27:08.192 UTC [69] FATAL:  role "root" does not exist
database-1  | 2024-04-18 06:28:08.352 UTC [71] FATAL:  role "root" does not exist
```
> fix healthcheck postgres user

- doctrine/doctrine-bundle/2.12/manifest.json
| Doc issue/PR  | [PR#1307](https://github.com/symfony/recipes/pull/1307)
As per discussed in https://github.com/symfony/recipes/pull/1307, the current healthcheck makes container always unhealthy. After testing every combination, the only implementations that produce healty status are the following:
```yaml
test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
```
and
```yaml
test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-app} -U ${POSTGRES_USER:-app} || exit 1"]
```
This PR uses the first approach.
> Fix healthcheck for database service

- doctrine/doctrine-bundle/2.12/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.12/manifest.json
Follows #1299 and #1302
Possible after https://github.com/symfony/symfony/pull/54720
Use explicit mappings instead, e.g.:
`#[Route('/conference/{id:conference}/{slug:conference}')]`
/cc @bobvandevijver we could now deprecate *enabling* automapping in doctrine-bundle. Up to send a PR doing so?
> [doctrine/doctrine-bundle] Disable automapping when using FWB >= 7.1

- symfony/go-ip-notifier/6.4/manifest.json
This has been forgotten to be set/enabled when the recipe was introduced for the first time.
> [Notifier] Enable auto-configuration for the `GoIP` bridge

- symfony/mercure-bundle/0.3/manifest.json
The Caddy config file name has changed in a previous version, see https://github.com/dunglas/mercure/issues/919 and https://mercure.rocks/docs/hub/install#docker-compose
cc @dunglas
> [MercureBundle] Change Caddy config filename

- symfony/sweego-mailer/7.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/20136
Related to https://github.com/symfony/symfony/pull/57431
PR for doc is coming
> feat(mailer): Add Sweego Mailer recipe

- symfony/framework-bundle/6.4/config/packages/framework.yaml
- symfony/framework-bundle/7.2/config/packages/framework.yaml
Not needed since https://github.com/symfony/symfony/pull/25508
> [symfony/framework-bundle] Remove "csrf_protection" line as its enabled by default

- symfony/framework-bundle/7.2/manifest.json
Follows #1342 
As spotted by @stof:
> As the .env.local file is not committed, the dev running the recipe will get the change, but it will be missing for everyone else in the team.
This PR stores the APP_SECRET in `.env.dev`, which is committed, but used only for the dev env.
> Generate APP_SECRET in .env.dev

- symfony/webpack-encore-bundle/2.0/package.json
- symfony/webpack-encore-bundle/2.0/post-install.txt
- symfony/webpack-encore-bundle/2.0/webpack.config.js
I'm about to release [Webpack Encore 5](https://github.com/symfony/webpack-encore/milestone/4) soon, so we must update the recipe.
**EDIT:** released!
> [WebpackEncoreBundle] Update recipe for Webpack Encore 5

- nelmio/security-bundle/2.4/config/packages/nelmio_security.yaml
This header is deprecated, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
We shouldn't enable it by default.
> [nelmio/security-bundle] Remove xss_protection config

- doctrine/doctrine-bundle/2.13/config/packages/doctrine.yaml
- doctrine/doctrine-bundle/2.13/manifest.json
- doctrine/doctrine-bundle/2.13/post-install.txt
| Doc issue/PR  |n/a
This recipe avoids getting deprecations from the ORM by turning on new settings.
For the identity generation precedence, using `identity` is the best choice for new projects (especially when using DBAL 4.x from the start).
Existing projects using DBAL 3.x should use the `sequence` value for this configuration setting to preserve the existing behavior (changing behavior is possible but requires a dedicated DB migration and can have visible changes in the application behavior as `sequence` pre-generates the id during `persist` while `identity` assigns the id only during the flush).
> Add a recipe for DoctrineBundle 2.13

- symfony/line-bot-notifier/7.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/20317
> Add LINE Bot notifier recipe

- symfony/sweego-notifier/7.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/20338
Following https://github.com/symfony/symfony/pull/58322, this PR adds the corresponding recipe.
> [Notifier] Add Sweego Bridge recipe

- zenstruck/browser/1.9/manifest.json
- zenstruck/browser/1.9/post-install.txt
Companion to https://github.com/zenstruck/browser/pull/156
I've been working on making it easier to get started using `zenstruck/browser` and `symfony/panther` together. Basically, adding a way to avoid [this "hack"](https://symfonycasts.com/screencast/last-stack/testing#loading-a-test-dev-server).
The fix in browser does the following:
1. Ensure a new webserver is always started by unsetting `SYMFONY_PROJECT_DEFAULT_ROUTE_URL`. This env var is added by the Symfony CLI when a server is running for the current project. For the most part, I think this is the user's dev environment which they don't want to run their tests on.
2. Set `PANTHER_APP_ENV` to `APP_ENV` to ensure the arrange/setup phase of your …
> Add recipe for `zenstruck/browser`

- zenstruck/foundry/2.0/config/packages/zenstruck_foundry.yaml
- zenstruck/foundry/2.0/manifest.json
- zenstruck/foundry/2.0/post-install.txt
Removes a deprecated config option.
> Add recipe for `zenstruck/foundry` 2.0

- symfony/mailer/4.3/manifest.json
Currently, when installing `symfony/mailer`, the `MAILER_DSN` is commented out so you get an error when trying to send an email. I feel this is a bit of a DX bummer.
I think it should default to `null://null` so you can start using it right away (preview in the profiler and use in your tests).
Any bridge you install for production sending would configure `MAILER_DSN` elsewhere (ie secrets or `.env.local`).
> uncomment `MAILER_DSN` env for `symfony/mailer`

- symfony/ux-google-map/2.19/manifest.json
- symfony/ux-leaflet-map/2.19/manifest.json
This PR fix options URLs in manifest.json for both Leaflet and Google Map
> [UX Map] Fix options URL

- symfony/ux-google-map/2.19/post-install.txt
- symfony/ux-google-map/2.22/manifest.json
- symfony/ux-google-map/2.22/post-install.txt
- symfony/ux-leaflet-map/2.19/post-install.txt
Follow https://github.com/symfony/ux/pull/2358, I've also added post-install steps.
Version 2.22 is not released yet, [but 2.19 is](https://packagist.org/packages/symfony/ux-google-map#v2.19.0)
> [Symfony UX Map] Add post-install steps for Leaflet and Google, add "ux_map.google_maps.default_map_id" config recipe

- symfony/asset-mapper/6.4/config/packages/asset_mapper.yaml
When working on my project with the AssetMapper, it became frustrating to found that my relative import didn't work because `.js` was missing at the end of the import path.
I wanted to implement something which tells the user to specify `.js` if we found that `<import path>.js` exists, but... the feature already exist, through `missing_import_mode` configuration.
The thing is, defaulting to `warn` (which warns import errors in the profiler) by default is not very useful. 
When you work locally on your project, you want errors to be displayed clearly so you can quickly fix them.
This PR updates the `missing_import_mode` to `strict` (so exceptions are thrown) on all environment, but …
> [AssetMapper] Re-configure "missing_import_mode" in prod/non-prod envs

- symfony/framework-bundle/7.2/config/packages/framework.yaml
- symfony/stimulus-bundle/2.20/assets/bootstrap.js
- symfony/stimulus-bundle/2.20/assets/controllers.json
- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
- symfony/stimulus-bundle/2.20/assets/controllers/hello_controller.js
- symfony/stimulus-bundle/2.20/manifest.json
- symfony/ux-turbo/2.20/manifest.json
Relies on https://github.com/symfony/symfony/pull/58095
> Enable stateless headers/cookies-based CSRF protection

- symfony/ux-turbo/2.19/manifest.json
- symfony/ux-turbo/2.20/manifest.json
| Doc issue/PR  | https://github.com/symfony/ux/issues/2391
Turbo is not installed correctly now (i guess now having this recipe, we do need to add the `bundles` entry in the manifest)
Issue: https://github.com/symfony/ux/issues/2391
The "conflict" should not prevent the bundle to be configured, as the same thing occurs in the Stimulus Bundle with no problem
---
**Update 1**: not enough 😢 
```
13 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
- Skipping recipe for symfony/ux-turbo: all versions of the recipe conflict with your package versions.
```
---
**Update2**: added a 2.19 recipe
---
**Update3**:  nope :/
It worked once, but i cannot make it work another time 🤔 
``` …
```
> [UX Turbo] Fix recipe does not install bundle

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
In addition to https://github.com/symfony/symfony/pull/59296
(see discussion there)
> [stimulus-bundle] Use defaultValue to change the value of hidden CSRF fields

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
Should ease upgrading apps. See https://github.com/symfony/symfony/issues/59111, https://github.com/symfony/symfony-docs/pull/20530 and https://github.com/symfony/maker-bundle/pull/1592
> [stimulus-bundle] Match name="_csrf_token" when looking for CSRF fields

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
| Q |	A 
| - | - |
| License | MIT
| Doc issue/PR | 	-
This allow support / compatibility with LiveComponent when action are done between form first render and submit 
(ex: another form submit with Turbo and double header check)
See https://github.com/symfony/ux/issues/2505
> [CSRF][StimulusBundle] Dispatch event on CSRF form field value change

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
Here is my first proposal addressing #1370:
* Fixes the issue where the CSRF token is updated after the form is submitted (e.g., when using fetch requests) ;
* Avoids code duplication when reusing this logic in multiple places ;
* Replaces `var` by `const` or `let` for better modern JavaScript practices.
This code can be used without Turbo. Here's an example:
```js
import { generateCsrfHeaders, removeCsrfToken } from './csrf_protection.js';
// ...
document.addEventListener('before-event-with-jquery-or-custom-fetch-event', function (event) {
Object.entries(generateCsrfHeaders(event.detail.form)).forEach(([name, value]) => {
// add header
});
});
document.addEventListener('after-event-with-jquery-or-custom-fe …
```
> [stimulus-bundle] Export CSRF protection helpers

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
PR #1375 had a typo, resulting in `Uncaught TypeError: formElement.querySelector is not a function`.
> [stimulus-bundle] Fix broken CSRF header generation with Turbo forms

- symfony/webpack-encore-bundle/1.10/package.json
- symfony/webpack-encore-bundle/1.9/package.json
https://github.com/symfony/stimulus-bridge/releases/tag/v4.0.0 has been released today, let's update the recipes containing this package.
> [WebpackEncoreBundle] Bump @symfony/stimulus-bridge to ^4.0.0

- easycorp/easyadmin-bundle/4.14/config/routes/easyadmin.yaml
- easycorp/easyadmin-bundle/4.14/manifest.json
This pull request adds a new route configuration for EasyAdmin in the `easyadmin.yaml` file. The new configuration defines autoload for new pretty URL
The support for pretty admin URLs was introduced in EasyAdmin 4.14.0.
> [EasyAdmin] Add pretty admin URL routes

- symfonycasts/tailwind-bundle/0.8/config/packages/symfonycasts_tailwind.yaml
- symfonycasts/tailwind-bundle/0.8/manifest.json
| Doc issue/PR  | https://github.com/SymfonyCasts/tailwind-bundle/pull/91
Starting with 0.8, not setting the exact version or path to a binary is deprecated.
Prior to 0.8, the latest tailwind was downloaded if not set explicitly. This was causing v4 to be downloaded on projects that don't support it. The easiest way to fix was to require an exact version be defined to *lock* the version your app uses.
> Add `symfonycasts/tailwind-bundle` recipe

- .github/workflows/callable-flex-cleanup.yml
- .github/workflows/callable-flex-update-archived.yml
- .github/workflows/callable-flex-update.yml
Update GitHub runner versions to use `ubuntu-latest`
See https://github.com/symfony/recipes/pull/1382
> Update "runs-on" to use ubuntu-latest instead of deprecated 20.04

- phpunit/phpunit/10.0/.env.test
- phpunit/phpunit/10.0/manifest.json
- phpunit/phpunit/10.0/phpunit.dist.xml
- phpunit/phpunit/10.0/tests/bootstrap.php
- phpunit/phpunit/4.7/tests/bootstrap.php
- phpunit/phpunit/9.3/tests/bootstrap.php
- phpunit/phpunit/9.6/tests/bootstrap.php
- symfony/panther/1.0/manifest.json
This will add a recipe for PHPUnit 10:
Following changes:
- `listeners` do not longer exists in PHPUnit 10  where replaced by extensions
- the old `extensions` still exists but need to be written differently
- they require `bootstrap` tag now: https://docs.phpunit.de/en/10.3/configuration.html#the-extensions-element and use the new event system https://docs.phpunit.de/en/10.3/extending-phpunit.html#phpunit-s-event-system (this effects maybe phpunit-bridge and panther)
- move from `phpunit.xml.dist` to `phpunit.dist.xml` for better IDE support (same already done for phpstan) see also: https://github.com/sebastianbergmann/phpunit/issues/4650 / …
> Add Recipe for PHPUnit 10

- symfony/webpack-encore-bundle/2.0/manifest.json
Currently if someones types "composer req ux" after a base symfony install ... he ends up with webpack encore.
Worse, the same thing happens if user installed symfony "--webapp", as they will end up with both AssetMapper and Webpack Encore installed.
Finally, and the initial reason I checked this: we will soon need the "ux" alias for the UX Bundle.
cc @Kocal 
PS: not sure if this would require a release to be effective... and hope it does not 😅
> [Webpack-Encore] Remove "ux" alias

- symfony/web-profiler-bundle/6.1/config/packages/web_profiler.yaml
Let's remove the defaults as they rarely need to be changed.
> Simplify web profile default config

- league/oauth2-server-bundle/0.11/config/packages/league_oauth2_server.yaml
- league/oauth2-server-bundle/0.11/config/routes/league_oauth2_server.yaml
- league/oauth2-server-bundle/0.11/manifest.json
- league/oauth2-server-bundle/0.11/post-install.txt
- Simplify post-install instructions about the key/pair generation which is now handled by a built-in console command
- Update the routes file path as the bundle upgraded its directory structure to the recommended, modern one.
/cc @ajgarlag
> [league/oauth2-server-bundle] Add v0.11 recipe

- phpunit/phpunit/10.0/phpunit.dist.xml
- phpunit/phpunit/10.0/tests/bootstrap.php
* The `failOnNotice`/`failOnWarning` options are part of PHPUnit's own recommended configuration file, I think it's worth adding these to our recommendation as well
* `restrictDeprecations="true"` only reports deprecations *triggered* by application code (which is not related to "direct" deprecations). We should not recommend it. PHPUnit 11 comes with the correct alternative (see https://github.com/symfony/recipes/pull/1401)
* `ignoreSuppressionOfDeprecations="true"` is a must-have for Symfony deprecations, given we silence all deprecation triggers.
* https://github.com/symfony/recipes/pull/889 was only applied to the PHPUnitBridge, I think we should add it to the PHPUnit recipe as …
> Make PHPUnit 10 config more consistent with PHPUnitBridge behavior

- doctrine/doctrine-bundle/1.12/manifest.json
- doctrine/doctrine-bundle/1.6/manifest.json
- doctrine/doctrine-bundle/2.0/manifest.json
- doctrine/doctrine-bundle/2.10/manifest.json
- doctrine/doctrine-bundle/2.12/manifest.json
- doctrine/doctrine-bundle/2.13/manifest.json
- doctrine/doctrine-bundle/2.3/manifest.json
- doctrine/doctrine-bundle/2.4/manifest.json
- doctrine/doctrine-bundle/2.8/manifest.json
- doctrine/doctrine-bundle/2.9/manifest.json
Since sqlite doesn't benefit from `doctrine.dbal.dbname_suffix`, this is required to not wipe your sqlite db when running tests.
> [doctrine/doctrine-bundle] add environment to sqlite DSN

- league/oauth2-server-bundle/0.11/manifest.json
I accidentally removed them from the manifest when adding the v0.11 recipe.
> [league/oauth2-server-bundle] Gitignore signature keypair

- zenstruck/foundry/2.5/config/packages/zenstruck_foundry.yaml
- zenstruck/foundry/2.5/manifest.json
- zenstruck/foundry/2.5/post-install.txt
update of Foundry's recipe for the new "flush_once" configuration which will land in `zenstruck/foundry` 2.5
/cc @kbond 
EDIT: CI is failing because it tries to update with `2.x-dev`, but it should use `2.5.x-dev`
> [zenstruck/foundry] introduce flush_once config

- symfony/framework-bundle/6.4/.editorconfig
- symfony/framework-bundle/6.4/manifest.json
- symfony/framework-bundle/7.2/.editorconfig
- symfony/framework-bundle/7.2/manifest.json
Fixes https://github.com/symfony/recipes/pull/1413#issuecomment-2886991608
> [symfony/framework-bundle] keep `.editorconfig` only in 7.3

- doctrine/deprecations/1.0/manifest.json
- phpunit/phpunit/11.1/.env.test
- phpunit/phpunit/11.1/bin/phpunit
- phpunit/phpunit/11.1/manifest.json
- phpunit/phpunit/11.1/phpunit.dist.xml
- phpunit/phpunit/11.1/post-install.txt
- phpunit/phpunit/11.1/tests/bootstrap.php
- symfony/phpunit-bridge/7.3/manifest.json
| Doc issue/PR  | I'll take care of this once we decide the direction for PHPUnit integration
This is a continuation of the effort to move the community towards PHPunit 11's deprecation features, in favor of the Symfony PHPUnit bridge. This is primarily based on what I submitted to the Symfony Demo a while ago: https://github.com/symfony/demo/pull/1549
This PR makes a couple important changes:
* **Add a recipe for PHPUnit 11.1+**. This version has a full replacement for the deprecation reporting capabilities of PhpunitBridge.
* **Change the recipe for PhpunitBridge 7.3 to no longer set-up testing (i.e. configure PHPUnit)**.
Continueing https://github.com/symfony/recipes/pull/906 from 4 years ago, the only reason you might …
> Add PHPUnit 11 recipe, treat PHPUnitBridge only as a PHPUnit extension

- symfony/framework-bundle/7.3/.editorconfig
Symfony follows docker compose suggestions with 2 indents on docker compose files and so requires an own sections to set it. For markdown the trim_trailing_whitespace need be disabled as two spaces in markdown at end of line means a line break. Added also a link to editorconfig.org so people not familiar with find it easy.
/cc @kbond
> Adjust editorconfig for docker compose and markdown files

- symfonycasts/tailwind-bundle/0.8/config/packages/symfonycasts_tailwind.yaml
> time to use v4

- symfony/panther/1.0/manifest.json
Related to https://github.com/symfony/flex/pull/1055
> [symfony/panther] Add requires for extension

- symfony/ux-live-component/2.6/manifest.json
- symfony/ux-turbo/2.20/manifest.json
- symfony/ux-twig-component/2.13/manifest.json
> [symfony/ux-*] add aliases

- symfony/stimulus-bundle/2.20/assets/controllers/csrf_protection_controller.js
closes https://github.com/symfony/symfony/issues/60983
> remove "useless" escape

- symfony/ux-turbo/2.20/manifest.json
Since https://github.com/symfony/recipes/commit/b06f1ce2f7c3f7d5cb18fcce68c08a02cc1b271c, the (stateless) CSRF configuration now lives in `config/packages/csrf.yaml` file:
```yaml
framework:
form:
csrf_protection:
token_id: submit
csrf_protection:
stateless_token_ids:
- submit
- authenticate
- logout
```
Some spaces from `target` and `content` were removed since we want to add `check_header: true` for [`framework.csrf_protection` configuration ](https://symfony.com/doc/current/reference/configuration/framework.html#check-header), which is one-level under `framework.form.csrf_protection`
> [Turbo] Fix `check_header` configuration

- symfony/ux-turbo/2.20/config/packages/ux_turbo.yaml
- symfony/ux-turbo/2.20/manifest.json
Following https://github.com/symfony/recipes/pull/1439#issuecomment-3122053728 
<details>
<summary>Old alternative with `position: 'bottom'`</summary>
The solution is fragile and kind of ugly (note the extra line before `check_header: true`, as it generates the following file:
```yaml
framework:
form:
csrf_protection:
token_id: submit
csrf_protection:
stateless_token_ids:
- submit
- authenticate
- logout
check_header: true
```
But it works: 
```
➜  app-flex-1440 git:(main) ✗ sfc debug:config framework csrf_protection
Current configuration for "framework.csrf_protection"
=====================================================
stateless_token_ids:
- submit
- authenticate
- logout …
```
> [Turbo] Correctly fix `framework.csrf_protection.check_header` configuration

- zenstruck/foundry/2.7/config/packages/zenstruck_foundry.yaml
- zenstruck/foundry/2.7/manifest.json
- zenstruck/foundry/2.7/post-install.txt
- zenstruck/foundry/2.7/src/Story/AppStory.php
| Doc issue/PR  | https://github.com/zenstruck/foundry/pull/943
ping @kbond
> [zenstruck/foundry] enable auto refresh with lazy objects in 2.7

- symfony/ai-bundle/0.1/config/packages/ai.yaml
- symfony/ai-bundle/0.1/manifest.json
Follows
* https://github.com/symfony/ai/pull/217
> Rename AIBundle to AiBundle

- symfony/panther/1.0/manifest.json
Following https://github.com/symfony/panther/issues/675 and https://github.com/symfony/ux/pull/2873, passing `PANTHER_DEVTOOLS=0` ([it is enabled by default](https://symfony.com/doc/current/testing/end_to_end.html#configuring-panther-through-environment-variables)) fixes issues when using Chrome 137+.
I agree this is not the best fix, surely something must be fixed upstream, but for the moment, disabling devtools allows Panther to be usable again in some situations.
> [Panther] Configure env `PANTHER_DEVTOOLS=0`

- symfony/routing/7.4/config/routes.yaml
One concern I have heard frequently regarding the use of attributes for routes is that it would be challenging to know the list of all routes in an application (unlike a dedicated routing file).
By adding these two lines of documentation, we are guiding developers toward the solution.
> Add doc about `debug:router`

- symfony/routing/7.0/config/packages/routing.yaml
- symfony/routing/7.0/manifest.json
Like database connection, domains are mostly managed OPS team and not by developers. To skip that the developer team need to keep in mind to add a env variable for the default_uri it would be nice if its out of the box a env variable exists – which can always be set by the ops team without have a developer to change the symfony app before.
> Add env variable for `router.default_uri` configuration option
