symfony/framework-bundle/3.3/Makefile
=> Enable interpretation of backslash escapes

phpunit/phpunit/4.7/phpunit.xml.dist
Once https://github.com/symfony/symfony/pull/22668 is merged.
=> [PhpUnit] Use the new KERNEL_CLASS var for KernelTestCase

symfony/profiler-pack/3.3/manifest.json, symfony/web-profiler-bundle/3.3/manifest.json
fixes symfony/flex#90
License MIT
=> Add the profiler pack

README.rst
=> updated recipe in README

README.rst
=> Remove extra comma in Full JSON Example

symfony/framework-bundle/3.3/Makefile
=> [framework-bundle] Fix bin/console exit code on error in Makefile

symfony/framework-bundle/3.3/Makefile
=> Fix the Makefile

easycorp/easy-log-handler/1.0/config/packages/dev/easy_log_handler.yaml, sensiolabs/security-checker/4.0/config/packages/dev/security_checker.yaml
=> Simplify service definitions

symfony/framework-bundle/3.3/config/packages/framework.yaml, symfony/framework-bundle/3.3/config/packages/test/framework.yaml, symfony/routing/3.3/config/packages/routing.yaml, symfony/security-bundle/3.3/config/packages/security.yaml
=> yaml: use `~` instead of `null`

symfony/console/3.3/bin/console
=> Fix use order in bin/console

symfony/flex/1.0/.env.dist
=> Replace indefinite article "an" -> "a"

doctrine/doctrine-bundle/1.6/manifest.json
=> Tweak letter case of "SQLite" and change article "a" -> "an"

symfony/framework-bundle/3.3/src/Kernel.php
=> Renamed var/logs/ to var/log/

symfony/framework-bundle/3.3/Makefile
=> Makefile: remove trailing dot on server:stop command

symfony/framework-bundle/3.3/Makefile
=> Uppercase the first letter in the printing message

symfony/flex/1.0/.env.dist
=> Reword .env.dist comment

twig/extensions/1.0/config/packages/twig_extensions.yaml, twig/extensions/1.0/manifest.json
=> Add twig-extensions extensions as services

symfony/webpack-encore-pack/1.0/manifest.json
=> Add node_modules in .gitignore

symfony/framework-bundle/3.3/config/services.yaml
Requires https://github.com/symfony/symfony/pull/24126
=> Public controllers

phpunit/phpunit/4.7/phpunit.xml.dist, symfony/phpunit-bridge/3.3/phpunit.xml.dist
=> Add default env vars for PHPUnit

symfony/framework-bundle/3.3/Makefile
Remove the semicolon unless it has been added for a specific reason.
=> Remove unnecessary semicolon

willdurand/js-translation-bundle/2.0/config/routes/js_translation.yaml, willdurand/js-translation-bundle/2.0/manifest.json
Disclaimer: I'm not a maintainer of this bundle
I think BazingaJsTranslationBundle is a good-quality bundle that deserves being in the "official" recipes repository. If you do not agree, I will open a PR on recipes-contrib instead.
=> Add recipe for BazingaJsTranslationBundle

symfony/framework-bundle/3.3/Makefile
=> Add some punctuations

symfony/webpack-encore-pack/1.0/package.json
* Add a license field to prevent a warning when running `yarn install`
* Make the package private by default to prevent accidental publishing on the NPM registry
=> [Encore] Improve the generate package.json

symfony/framework-bundle/3.3/Makefile
=> Fix space issue in bin/console

symfony/framework-bundle/3.3/Makefile
=> Fix logic in Makefile

symfony/framework-bundle/3.3/Makefile
Alternative to #202, reverts #200 and #201.
=> Fix Makefile

javiereguiluz/easyadmin-bundle/1.16/manifest.json, javiereguiluz/easyadmin-bundle/1.17/config/packages/easy_admin.yaml, javiereguiluz/easyadmin-bundle/1.17/config/routes/easy_admin.yaml, javiereguiluz/easyadmin-bundle/1.17/manifest.json
From 1.16 to 1.17 we updated the namespace from `JavierEguiluz\...` to `EasyCorp\...`. In the coming days/weeks we'll also move the repository vendor from `javiereguiluz/...` to `easycorp/...` so I'll need to create a new recipe under a different vendor.
=> Updated the admin recipe for the new version of the bundle

symfony/security-bundle/3.3/config/packages/security.yaml, symfony/security-bundle/3.3/config/packages/test/security.yaml
Just a proposal. This is a common practice in Symfony apps and it's was surprising not having it when upgrading the Symfony Demo to use Flex.
=> Proposed a security.yaml file for the "test" environment

symfony/framework-bundle/3.3/Makefile
=> Add some command names for make help

lexik/jwt-authentication-bundle/2.3/Makefile
=> Added default information

symfony/phpunit-bridge/3.3/manifest.json
=> Add simple-phpunit alias

symfony/framework-bundle/3.3/manifest.json
=> when make is gone, composer should use symfony console command

lexik/jwt-authentication-bundle/2.3/post-install.txt
=> Remove obsolete post-install

doctrine/doctrine-bundle/1.6/manifest.json
=> Fix doubled quotes

symfony/translation/3.3/config/packages/translation.yaml, symfony/translation/3.3/manifest.json
To reflect default path choice made in https://github.com/symfony/symfony/pull/24860.
=> Move translation dir to config/translations

symfony/maker-bundle/1.0/manifest.json
=> Add maker-bundle recipe

symfony/maker-bundle/1.0/manifest.json
Proposing `make` alias as it's the console namespace of the commands included
=> Propose make alias

phpunit/phpunit/4.7/phpunit.xml.dist, symfony/phpunit-bridge/3.3/phpunit.xml.dist
Replaces #242 and #248, needs https://github.com/symfony/symfony/pull/25162 to be fully effective.
=> Set SHELL_VERBOSITY to "-1" (quiet)

phpunit/phpunit/4.7/manifest.json, symfony/phpunit-bridge/3.3/manifest.json
=> Add a tests/ for for phpunit-related recipes

symfony/serializer-pack/1.0/manifest.json, symfony/serializer/3.3/manifest.json
See also https://github.com/dunglas/serializer-pack/
=> Add symfony/serializer-pack

symfony/phpunit-bridge/3.3/manifest.json
=> gitignore /bin/.phpunit

phpunit/phpunit/4.7/phpunit.xml.dist
=> Clean symfony from PHPUnit library

doctrine/annotations/1.0/config/routes/annotations.yaml
Requires https://github.com/symfony/symfony/pull/25113
=> Use config-relative path for routing annotation resources

symfony/webpack-encore-pack/1.0/manifest.json
=> Ignoring the Encore build directory

symfony/flex/1.0/git/HEAD, symfony/flex/1.0/git/config, symfony/flex/1.0/manifest.json
=> Add local empty git repo by default

nelmio/cors-bundle/1.5/config/packages/nelmio_cors.yaml, nelmio/cors-bundle/1.5/manifest.json
Adds a recipe as well as an official alias for [NelmioCorsBundle](https://github.com/nelmio/NelmioCorsBundle).
=> Add a recipe for NelmioCorsBundle

symfony/webpack-encore-pack/1.0/package.json
Reason: https://github.com/symfony/webpack-encore/issues/226#issuecomment-352292127
=> Change webpack-encore version

friendsofphp/php-cs-fixer/2.2/manifest.json
=> PHP CS Fixer: add fixer alias

symfony/framework-bundle/3.3/config/packages/framework.yaml
Hi guys!
I'm open to suggestions to make this better. I thought it would be useful to give people some great caching options just by showing them here. I think it's important because the keys you need to use (e.g. `cache.adapter.apcu`) are abstract. So let's make it as easy as possible.
=> suggesting other cache options

symfony/framework-bundle/3.3/config/packages/framework.yaml
=> Tweak cache-related section

sensiolabs/security-checker/4.0/config/packages/dev/security_checker.yaml
=> Lazy load security:check command

symfony/security-bundle/3.3/config/packages/security.yaml, symfony/swiftmailer-bundle/2.5/config/packages/dev/swiftmailer.yaml
=> Minor fixes in the comments of some recipes

symfony/framework-bundle/3.3/config/packages/framework.yaml
=> [symfony/framework-bundle] Tell about the cache.prefix_seed setting

phpunit/phpunit/4.7/phpunit.xml.dist
Just a simple tweak for consistency
=> Make test suite dir consistent with whitelisted one

symfony/framework-bundle/3.3/config/services.yaml
=> Exclude the kernel when registering services

doctrine/doctrine-bundle/1.6/manifest.json
=> [doctrine-bundle] add single quotes for DATABASE_URL

symfony/framework-bundle/3.3/public/index.php
Fixes https://github.com/symfony/skeleton/issues/60
=> Fixed typo

symfony/phpunit-bridge/3.3/manifest.json, symfony/test-pack/1.0/manifest.json
=> Added symfony/test-pack

lexik/jwt-authentication-bundle/2.3/manifest.json, symfony/framework-bundle/3.3/manifest.json, symfony/web-server-bundle/3.3/manifest.json, symfony/webpack-encore-pack/1.0/manifest.json
=> Fix .gitignore file

lexik/jwt-authentication-bundle/2.3/config/packages/lexik_jwt_authentication.yaml
Use the same style than in other "official" YAML files.
=> [jwt] Uniformize YAML files's indentation

symfony/webpack-encore-pack/1.0/package.json
=> Update Webpack Encore version

symfony/framework-bundle/3.3/manifest.json
=> Remove "--relative" and "--symlink" options by default

api-platform/core/2.1/post-install.txt
Fixes api-platform/api-platform#657.
=> API Platform: add a post install message

symfony/flex/1.0/git/HEAD, symfony/flex/1.0/git/config, symfony/flex/1.0/manifest.json, symfony/framework-bundle/3.3/post-install.txt
Fixes https://github.com/symfony/flex/issues/373
=> Remove empty git repository

symfony/framework-bundle/3.3/config/services.yaml
=> [FrameworkBundle] Added DependencyInjection to the excluded directory list

symfony/validator/4.1/config/packages/validator.yaml
=> [symfony/validator] Fix config

symfony/messenger/4.1/post-install.txt
=> Fix a typo in the symfony/messenger post install text

symfony/framework-bundle/4.2/config/packages/framework.yaml, symfony/framework-bundle/4.2/config/packages/test/framework.yaml, symfony/framework-bundle/4.2/config/services.yaml, symfony/framework-bundle/4.2/manifest.json, symfony/framework-bundle/4.2/post-install.txt, symfony/framework-bundle/4.2/public/index.php, symfony/framework-bundle/4.2/src/Kernel.php
Enabling https://github.com/symfony/symfony/pull/28244 and https://github.com/symfony/symfony/pull/28168 by default.
=> [symfony/framework-bundle] Secure session defaults with "cookie_secure: auto" and "cookie_samesite: lax"

symfony/phpunit-bridge/3.3/phpunit.xml.dist, symfony/phpunit-bridge/4.1/phpunit.xml.dist
To keep in sync with [phpunit.xml.dist](https://github.com/symfony/recipes/blob/master/phpunit/phpunit/4.7/phpunit.xml.dist), see https://github.com/symfony/recipes/pull/349
=> Remove leading and trailing slashes in phpunit.xml.dist

symfony/framework-bundle/4.2/config/services.yaml
=> Remove "private" from defaults, it already is

symfony/webpack-encore-pack/1.0/package.json
=> [WebpackEncore] Display progress for prod build by default

doctrine/doctrine-fixtures-bundle/3.0/src/DataFixtures/AppFixtures.php
=> [Fixtures] Create a AppFixtures fixtures instead of .gitignore

symfony/flex/1.0/manifest.json
I missed this detail in #482! My bad!
=> adding missed manifest entry

symfony/framework-bundle/4.2/src/Kernel.php
aligns with latest iteration of https://github.com/symfony/symfony/pull/29154
=> fix namespace

symfony/framework-bundle/4.2/src/Kernel.php
=> Remove setting container.autowiring.strict_mode to true

symfony/framework-bundle/4.2/src/Kernel.php
=> Handle disabling bundles when config set to false

phpunit/phpunit/4.7/phpunit.xml.dist, symfony/framework-bundle/3.3/src/Kernel.php, symfony/phpunit-bridge/3.3/phpunit.xml.dist
Matches https://github.com/symfony/symfony/pull/29171
=> Load .env.dist when it exists and .env is not found

phpunit/phpunit/4.7/.env.test, phpunit/phpunit/4.7/phpunit.xml.dist, symfony/phpunit-bridge/3.3/.env.test, symfony/phpunit-bridge/3.3/phpunit.xml.dist, symfony/phpunit-bridge/4.1/.env.test
Fixes https://github.com/symfony/symfony/issues/29241
=> Move silencing to phpunit.xml.dist

symfony/framework-bundle/3.3/manifest.json, symfony/framework-bundle/3.3/public/index.php, symfony/framework-bundle/4.2/manifest.json, symfony/framework-bundle/4.2/public/index.php
=> TRUSTED_HOSTS is a regexp

symfony/var-dumper/3.3/manifest.json
=> Add "dump" alias to install "symfony/var-dumper"

nelmio/alice/3.2/config/packages/dev/nelmio_alice.yaml
Hi, I added a few PHP native functions to blacklist, as they should be overridden by fzaninotto/faker.
=> Nelmio Alice: blacklist PHP native functions that match formatters

twig/cssinliner-extension/1.0/manifest.json
=> Add the cssinliner extension for Twig

twig/inky-extension/1.0/manifest.json, twig/markdown-extension/1.0/manifest.json
=> Add the Markdown and Inky Twig extensions

nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml, nyholm/psr7/1.0/manifest.json
=> Add nyholm/psr7 to the official recipes

README.rst
As discussed in https://github.com/symfony/symfony-docs/pull/11114, we could expand the explanation of placeholders.
=> Better explain the placeholders in the README

symfony/mailer/4.3/config/packages/mailer.yaml, symfony/mailer/4.3/manifest.json, symfony/mailer/4.3/post-install.txt
=> Add a recipe for Symfony mailer

symfony/framework-bundle/3.3/src/Kernel.php
=> Load routes for specific env first (bis)

symfony/messenger/4.1/manifest.json
=> Added conflict for messenger recipe

symfony/validator/4.1/config/packages/test/validator.yaml
=> [Symfony][Validator] Added option disable_not_compromised_password

symfony/framework-bundle/3.3/post-install.txt, symfony/framework-bundle/4.2/post-install.txt
=> Suggest installing the Symfony CLI instead of using the built-in PHP web server

symfony/framework-bundle/3.3/config/bootstrap.php, symfony/framework-bundle/4.2/config/bootstrap.php
Related to https://github.com/symfony/symfony/pull/31062#pullrequestreview-225045445
=> Dont use putenv by default

symfony/phpunit-bridge/4.1/bin/phpunit, symfony/phpunit-bridge/4.1/phpunit.xml.dist
Fixes https://github.com/symfony/recipes/pull/561, related to https://github.com/symfony/symfony/pull/31210
=> Move configuring SYMFONY_PHPUNIT_VERSION to phpunit.xml.dist

symfony/messenger/4.3/config/packages/messenger.yaml, symfony/messenger/4.3/manifest.json, symfony/messenger/4.3/post-install.txt
Minor tweaks while playing with the Messenger documentation today :). 
Cheers!
=> Tweaks to messenger 4.3 recipe

symfony/mailer/4.3/manifest.json, symfony/mailer/4.3/post-install.txt, symfony/swiftmailer-bundle/2.5/manifest.json
Time to celebrate 4.3's arrival!
=> Changing mailer alias to Mailer component

.github/PULL_REQUEST_TEMPLATE.md
Recipes often have consequences for the docs. Let's get into the habit of making sure there is a related docs issue or PR if one is needed.
Cheers!
=> Proposing a docs issue/PR on PR template

symfony/validator/4.3/config/packages/validator.yaml
See https://github.com/symfony/maker-bundle/issues/412
=> Disable auto-mapping for now

symfony/framework-bundle/4.2/post-install.txt
see https://github.com/symfony/symfony/pull/31217
=> feature: deprecate WebserverBundle and remove it from the recipe message

symfony/messenger/4.3/config/packages/messenger.yaml
Minor change, the url anchor seems to not be correct
=> [Messenger] update doc url

behat/symfony2-extension/2.1/features/bootstrap/FeatureContext.php
To make the file more compliant with PSR2 then I'm removing the whitespace found at the end of the lines
=> Remove whitespace to make more compliant with PSR2

doctrine/doctrine-bundle/1.6/manifest.json
=> [doctrine-bundle] Update URL to use HTTPS and avoid redirection

symfony/phpunit-bridge/4.1/manifest.json
=> [PhpUnitBridge] git ignore result cache

nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml
=> Register nyholm/psr7 services for autowiring with HTTPlug factories

README.rst, nelmio/cors-bundle/1.5/config/packages/nelmio_cors.yaml, sensiolabs/security-checker/4.0/config/packages/security_checker.yaml, symfony/framework-bundle/3.3/config/packages/cache.yaml, symfony/framework-bundle/3.3/config/packages/framework.yaml, symfony/framework-bundle/4.2/config/packages/framework.yaml, symfony/routing/3.3/config/packages/routing.yaml, symfony/routing/4.0/config/packages/routing.yaml, symfony/routing/4.2/config/packages/routing.yaml, symfony/security-bundle/3.3/config/packages/security.yaml, symfony/workflow/3.3/config/packages/workflow.yaml, twig/extensions/1.0/config/packages/twig_extensions.yaml
Use `null` instead of `~` in the recipes.
=> Replace ~ by null

symfony/webpack-encore-bundle/1.0/config/packages/webpack_encore.yaml
A little fix with trailing space
=> Remove trailing whitespace

symfony/security-bundle/4.4/config/packages/security.yaml, symfony/security-bundle/4.4/manifest.json
Needs https://github.com/symfony/symfony/pull/33676
=> [security-bundle] enable anonymous: lazy by default

doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.6/manifest.json
=> Add a DSN example for psql

symfony/twig-bundle/3.3/manifest.json, symfony/twig-pack/1.0/manifest.json
=> Add support for the Twig extra bundle

symfony/flex/1.0/.env
Changed the word later to latter.
=> Fixed small typo in .env file

symfony/notifier/5.0/config/packages/notifier.yaml, symfony/notifier/5.0/manifest.json
=> Add a recipe for Notifier

symfony/framework-bundle/4.4/config/secrets/prod/.gitignore
To merge after https://github.com/symfony/symfony/pull/33997
=> [framework-bundle] git-ignore prod.sodium.decrypt.private

nelmio/cors-bundle/1.5/manifest.json
=> Allow 127.0.0.1 in CORS

symfony/framework-bundle/4.4/config/secrets/prod/.gitignore
Follow up of https://github.com/symfony/symfony/pull/34295
=> Update gitignore in config/secrets/prod

symfony/framework-bundle/4.2/manifest.json
Closes https://github.com/symfony/symfony/issues/33578
=> Trust proxies on private and local IPs (commented by default)

.travis.yml
=> Adding tests on Symfony5

symfony/framework-bundle/4.2/manifest.json, symfony/framework-bundle/4.4/config/secrets/prod/.gitignore
=> Dont create config/secrets/ by default

symfony/flex/1.0/.env
=> Fix broken link in .env file

symfony/framework-bundle/4.2/config/bootstrap.php
| Branch?       | > 4.1 
| Bug fix?       | yes
| Ticket       | #35293
Fix error synthax in bootstrap.php line 9, too much bracket.
=> Fix error synthax in bootstrap.php

symfony/framework-bundle/3.3/config/bootstrap.php
=> fix PHP syntax error

symfony/console/3.3/bin/console, symfony/console/4.4/bin/console, symfony/phpunit-bridge/3.3/manifest.json
=> Some cleanups

symfony/framework-bundle/4.2/config/bootstrap.php
=> Fix loading .env.local.php

symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml, symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml
We want to prevent memory leaks. 
Reference: https://github.com/symfony/symfony/issues/35426
=> [Monolog] Add buffer_size on fingers_crossed handler

symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml
Follows #736 
Sorry for the two PR's I used the Github UI in this case ;-)
=> Remove space

symfony/framework-bundle/5.1/src/Kernel.php
| Doc issue/PR  | TODO
Following https://github.com/symfony/symfony/pull/30501.
=> [FrameworkBundle] Added the new RoutingConfigurator

symfony/twilio-notifier/5.0/manifest.json
#753 adds a recipe for Twilio Notifier
=> Add Twilio Notifier recipe

symfony/telegram-notifier/5.0/manifest.json
#753 adds a Telegram Notifier recipe
=> Add Telegram Notifier recipe

symfony/mattermost-notifier/5.1/manifest.json
#753 adds a recipe for Mattermost Notifier
=> Add Mattermost Notifier recipe

symfony/ovh-cloud-notifier/5.1/manifest.json
#753 adds a recipe for OvhCloud Notifier
=> Add OvhCloud Notifier recipe

symfony/rocket-chat-notifier/5.1/manifest.json
#753 add a recipe for RocketChat Notifier
=> Add RocketChat Notifier recipe

symfony/sinch-notifier/5.1/manifest.json
#753 adds a Sinch Notifier recipe
=> Add Sinch Notifier recipe

symfony/slack-notifier/5.0/manifest.json, symfony/slack-notifier/5.1/manifest.json
I've started this PR with the Slack notifier (also the most "complex" as 5.0 and 5.1 don't have the same DSN pattern), but I need help for the other ones:
Who wants to help? Comment here and send me a PR on this PR.
=> Added notifier bridge recipes

symfony/firebase-notifier/5.0/manifest.json
#753 adds a recipe for Firebase Notifier after contacting createor of the bridge [in this comment](https://github.com/symfony/recipes/pull/753#issuecomment-612861305)
=> Add Firebase Notifier recipe

symfony/webpack-encore-bundle/1.0/package.json
Encore has a new release - this uses it as the default :).
Thanks!
=> bumping encore to newest version

symfony/framework-bundle/3.3/public/index.php, symfony/framework-bundle/4.2/public/index.php, symfony/framework-bundle/4.4/public/index.php, symfony/framework-bundle/5.1/public/index.php
The lines before these ones ensure that `$_ENV` is merged into `$_SERVER` already.
=> [symfony/framework-bundle] minor cleanup

symfony/webpack-encore-bundle/1.0/package.json
New Encore version - 0.30.0 :).
Cheers!
=> Using latest Encore version

symfony/framework-bundle/5.1/src/Kernel.php
=> check for PHP files to exist before requiring them

symfony/framework-bundle/4.2/config/services.yaml, symfony/framework-bundle/4.4/config/services.yaml, symfony/framework-bundle/5.1/config/services.yaml
* This reverts commit 0903d762e95345b605fd81127e191d6f2c9acca9, reversing
changes made to 0800a647a44da5bdbe8a2edc42f32cb3d294a60f.
* This override `services.yaml` for symfony 4.4+
fixes #803
=> Revert "Merge pull request #802" - ONLY for Symfony 4.3 and 4.4

symfony/google-chat-notifier/5.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14018
Add the new component, as asked by @fabpot https://github.com/symfony/symfony/pull/36488#issuecomment-671386673
=> Add symfony/google-chat-notifier recipe

symfony/mailjet-mailer/5.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14095
This adds recipe for Mailjet mailer ref: [symfony/symfony#36541 (comment)](https://github.com/symfony/symfony/pull/36541#issuecomment-671387382)
=> [symfony/mailjet-mailer] Add recipe

symfony/infobip-notifier/5.2/manifest.json
=> Add DSN support for Infobip

symfony/esendex-notifier/5.2/manifest.json
| Doc issue/PR  | -    
See symfony/symfony#36573
=> Create recipe for symfony/esendex-notifier

symfony/infobip-notifier/5.2/manifest.json
To match the one in the readme.
=> Update Infobip DSN

symfony/framework-bundle/4.2/manifest.json, symfony/framework-bundle/5.2/manifest.json
Maps to https://github.com/symfony/symfony/pull/38063
=> List .preload.php in .gitignore

symfony/framework-bundle/4.2/manifest.json, symfony/framework-bundle/5.2/manifest.json
Follows https://github.com/symfony/symfony/pull/38142
=> Adopt src/.preload.php

symfony/sendinblue-notifier/5.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14301
=> [Notifier] Added Sendinblue bridge recipe

symfony/framework-bundle/5.1/src/Kernel.php
Bracket are not needed since we can be sure the file exist
=> [FrameworkBundle] Simplify the service and route registration

symfony/discord-notifier/5.2/manifest.json
| Doc issue/PR  | symfony/symfony-docs#13558   symfony/symfony#36475
Add a recipe for the discord notifier
=> Add Discord notifier recipe

symfony/mercure-bundle/0.1/manifest.json, symfony/messenger/4.1/manifest.json, symfony/messenger/4.3/manifest.json
=> Fix docker-compose recipes

doctrine/doctrine-bundle/1.6/manifest.json
| Doc issue/PR  | None 
Ref https://github.com/symfony/recipes/pull/113#discussion_r525028113
=> Fix docker-compose database service name

sensiolabs/ansi-to-html/1.2/config/packages/ansi_to_html.yaml, sensiolabs/ansi-to-html/1.2/manifest.json
=> Add sensiolabs/ansi-to-html recipe

doctrine/doctrine-bundle/1.6/manifest.json
=> Remove extra quotes

symfony/webpack-encore-bundle/1.0/assets/app.js, symfony/webpack-encore-bundle/1.0/assets/bootstrap.js, symfony/webpack-encore-bundle/1.0/assets/controllers.json, symfony/webpack-encore-bundle/1.0/assets/controllers/hello_controller.js, symfony/webpack-encore-bundle/1.0/package.json, symfony/webpack-encore-bundle/1.0/webpack.config.js
Add Stimulus in Webpack Encore recipe for Symfony UX support
=> Add Stimulus in Webpack Encore recipe

symfony/webpack-encore-bundle/1.6/config/packages/webpack_encore.yaml
=> Fix the way HTTP/2 is written

symfony/requirements-checker/1.0/manifest.json, symfony/requirements-checker/1.0/public/check.php
=> Remove using "copy-from-package"

symfony/slack-notifier/5.2/manifest.json
=> [Notifier] [Slack] Update DSN

symfony/iqsms-notifier/5.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#14555
cc @alexandrbarabolia
refs https://github.com/symfony/symfony/pull/39096
=> Add recipe for symfony/iqsms-notifier

symfony/gatewayapi-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony/pull/39568
=> Add symfony/gatewayapi-notifier

symfony/octopush-notifier/5.3/manifest.json
| Doc issue/PR  | symfony/symfony#39702
=> Add Octopush notifier transport

symfony/google-chat-notifier/5.3/manifest.json
| PR  | https://github.com/symfony/symfony/pull/39579
cc @GromNaN
=> Rename parameter for symfony/google-chat-notifier

README.rst
=> Clarify how to update recipes

symfony/webpack-encore-bundle/1.0/package.json
Just a little oversight I think :).
=> making package.json alphabetical

symfony/mercure-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14840
=> [Notifier] Add Mercure notifier recipe

symfony/clickatell-notifier/5.3/manifest.json
Add recipe for the clickatell notifier
Recipe for the PR https://github.com/symfony/symfony/pull/38922
=> Add recipe for the clickatell notifier

symfony/gitter-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/14835
=> Add symfony/gitter-notifier recipe

symfony/twig-bundle/3.3/templates/base.html.twig, symfony/webpack-encore-bundle/1.9/post-install.txt
I'm working on Symfony UX and I think the onboarding when using  Encore can be improved. Here is a first step.
=> Improve onboarding when using Encore

symfony/psr-http-message-bridge/2.1/config/packages/psr_http_message_bridge.yaml, symfony/psr-http-message-bridge/2.1/manifest.json
A recipe to integrate symfony/psr-http-message-bridge#89
=> Added a recipe for psr-http-message-bridge

symfony/webpack-encore-bundle/1.9/post-install.txt
=> Fixing closing tag in post install message

doctrine/doctrine-bundle/1.6/manifest.json
this makes next command execute only if the prior one is successful, otherwise all commands will execute
=> [doctrine-bundle] dockerfile: use && instead of ; to chain sh commands

README.rst
| Doc issue/PR  | N/A   
Improve formatting for json code block with comments. Before:
After:
=> Update syntax format for code block

symfony/fake-sms-notifier/5.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#14870
=> Add recipe for FakeSms Notifier bridge

symfony/mercure-notifier/5.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/15179
=> [Notifier] Mercure bridge: bump mercure dependency to 0.5

symfony/webpack-encore-bundle/1.0/assets/bootstrap.js
| Doc issue/PR  | not needed
Hi!
If you want to add a 3rd party controller, this change makes it much easier and more obvious :).
Thanks!
=> Making it easier and more obvious how to add extra stimulus controllers

symfony/framework-bundle/5.3/config/packages/framework.yaml, symfony/framework-bundle/5.3/config/packages/test/framework.yaml, symfony/framework-bundle/5.3/config/routes/dev/framework.yaml, symfony/framework-bundle/5.3/config/routes/framework.yaml
Leverages https://github.com/symfony/symfony/pull/40214
=> [framework-bundle/5.3] Merge per-env settings

symfony/fake-chat-notifier/5.3/manifest.json
| Doc issue/PR  | shttps://github.com/symfony/symfony-docs/pull/15171
=> Add symfony/fake-chat-notifier

symfony/fake-chat-notifier/5.3/manifest.json, symfony/fake-sms-notifier/5.3/manifest.json
| Doc issue/PR  | ---
Follows symfony/symfony#40739
=> [Notifier] [FakeSms] [FakeChat] Fix DSN

symfony/framework-bundle/5.3/config/services.yaml
=> Update best practices parameters link

symfony/lightsms-notifier/5.0/manifest.json, symfony/sms-biuras-notifier/5.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#15219
=> [Notifier] Sms Biuras

symfony/message-bird-notifier/5.3/manifest.json
https://github.com/symfony/symfony/pull/40646
=> [Notifier] MessageBird

symfony/debug-bundle/4.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony/issues/33312
Before:
After:
=> [DebugBundle] Do not enable it in test env

doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.4/manifest.json, doctrine/doctrine-bundle/2.4/post-install.txt
As discussed in https://github.com/symfony/recipes/pull/939#discussion_r629363629
=> Update note about server version

symfony/crowdin-translation-provider/5.3/manifest.json, symfony/loco-translation-provider/5.3/manifest.json, symfony/lokalise-translation-provider/5.3/manifest.json, symfony/translation/5.3/config/packages/translation.yaml, symfony/translation/5.3/manifest.json
This PR adds recipes for the new Translation Providers, added in 5.3 (https://github.com/symfony/symfony/pull/38475)
cc @fabpot @nicolas-grekas @Nyholm
=> Added the 3 first Translation Providers

symfony/routing/5.3/config/packages/routing.yaml, symfony/routing/5.3/config/routes.yaml, symfony/routing/5.3/manifest.json
Leverages symfony/symfony#40214
=> [Routing] Merge per-env settings for 5.3

phpunit/phpunit/9.3/phpunit.xml.dist, symfony/phpunit-bridge/5.3/phpunit.xml.dist
=> [phpunit] set convertDeprecationsToExceptions to false

symfony/message-media-notifier/5.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/15366
=> [Notifier] [MessageMedia] add recipe

symfony/telnyx-notifier/5.4/manifest.json
=> [Notifier] Telnyx

.github/workflows/qa.yml
=> Compute diff between recipe versions

symfony/twig-bundle/5.4/config/packages/twig.yaml, symfony/twig-bundle/5.4/manifest.json, symfony/twig-bundle/5.4/templates/base.html.twig
| Doc issue/PR  | https://github.com/symfony/symfony-docs/issues/15457
Needs https://github.com/symfony/symfony/pull/41205
=> [twig-bundle] uncomment `encore_*_tags()` when 5.4 is used

.github/workflows/create-project.yml
=> Set min-stab to dev in create-project job

symfony/smsc-notifier/5.4/manifest.json
| Doc issue/PR  | symfony/symfony-docs#15536
=> [Notifier] Add bridge for smsc.ru

symfony/yunpian-notifier/5.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/15553
Recipe for PR https://github.com/symfony/symfony/pull/42239
=> Add recipe for Yunpian notifier bridge

symfonycorp/platformsh-meta/1.0/.platform.app.yaml, symfonycorp/platformsh-meta/1.0/.platform/routes.yaml, symfonycorp/platformsh-meta/1.0/.platform/services.yaml, symfonycorp/platformsh-meta/1.0/config/packages/messenger.yaml, symfonycorp/platformsh-meta/1.0/manifest.json, symfonycorp/platformsh-meta/1.0/php.ini, symfonycorp/platformsh-pack/1.0/manifest.json
=> Add recipe for platformsh

symfonycorp/platformsh-meta/1.0/.platform.app.yaml
=> [platformsh] Add a cron that automatically check for security issues in prod

symfony/framework-bundle/5.4/src/Kernel.php
Since https://github.com/symfony/symfony/pull/42991
=> Kernel can be empty in 5.4

symfony/kaz-info-teh-notifier/6.1/manifest.json
| Doc issue/PR  | symfony/symfony-docs#16088
=> [Notifier] [Bridge] [KazInfoTeh] add manifest

doctrine/doctrine-bundle/2.4/manifest.json, symfony/routing/5.3/manifest.json, symfony/routing/6.0/manifest.json, symfony/security-bundle/5.3/manifest.json, symfony/twig-bundle/5.3/manifest.json, symfony/twig-bundle/5.4/manifest.json
Fix https://github.com/doctrine/DoctrineBundle/issues/1474 and similar.
=> Conflict with fwb < 5.3 when@env

hautelook/alice-bundle/2.2/config/packages/hautelook_alice.yaml, hautelook/alice-bundle/2.2/manifest.json, hautelook/alice-bundle/2.2/post-install.txt, nelmio/alice/3.3/config/packages/nelmio_alice.yaml, nelmio/alice/3.3/manifest.json, symfony/validator/5.3/config/packages/validator.yaml, symfony/validator/5.3/manifest.json, symfony/web-profiler-bundle/5.3/config/packages/web_profiler.yaml, symfony/web-profiler-bundle/5.3/config/routes/web_profiler.yaml, symfony/web-profiler-bundle/5.3/manifest.json, zenstruck/foundry/1.10/config/packages/zenstruck_foundry.yaml, zenstruck/foundry/1.10/manifest.json, zenstruck/foundry/1.10/post-install.txt
=> Consistently use when@env

symfony/webpack-encore-bundle/1.10/assets/app.js, symfony/webpack-encore-bundle/1.10/assets/bootstrap.js, symfony/webpack-encore-bundle/1.10/assets/controllers.json, symfony/webpack-encore-bundle/1.10/assets/controllers/hello_controller.js, symfony/webpack-encore-bundle/1.10/assets/styles/app.css, symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml, symfony/webpack-encore-bundle/1.10/manifest.json, symfony/webpack-encore-bundle/1.10/package.json, symfony/webpack-encore-bundle/1.10/post-install.txt, symfony/webpack-encore-bundle/1.10/webpack.config.js
=> Remove instruction to "uncomment" in webpack-encore-bundle recipe

symfony/turbo-sms-notifier/5.4/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/15403
=> Add manifest for turbo-sms-notifier

doctrine/doctrine-bundle/1.12/manifest.json, doctrine/doctrine-bundle/1.6/manifest.json, doctrine/doctrine-bundle/2.0/manifest.json, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.4/manifest.json, symfony/mercure-bundle/0.3/manifest.json
Use symfony coding standard of yml files with 4 spaces.
=> Update spacing of doctrine yml files

league/flysystem-bundle/1.0/config/packages/flysystem.yaml, league/flysystem-bundle/1.0/manifest.json, league/flysystem-bundle/1.0/post-install.txt
This bundle is the de facto Symfony integration of the quite popular league/flysystem lib, and it's led by @tgalopin who is now part of the core team. I propose to make this community recipe an official one.
=> Make league/flysystem-bundle an official recipe

symfony/sendberry-notifier/6.1/manifest.json
| Doc issue/PR  | symfony/symfony-docs#16452
=> [Notifier] Sendberry

symfony/engagespot-notifier/5.4/manifest.json
| Doc issue/PR  | symfony/symfony-docs#16165
This recipe is needed for https://github.com/symfony/symfony/pull/44303
=> [Notifier] Add Engagespot recipe

zenstruck/foundry/1.10/manifest.json
=> [zenstruck/foundry] add "foundry" alias

.github/workflows/flex-update.yml, README.rst
| Doc issue/PR  | none
To be merged after #1078.
=> Partner GH action workflow for updating RECIPES.md

symfony/routing/6.1/config/packages/routing.yaml, symfony/routing/6.1/config/routes.yaml, symfony/routing/6.1/manifest.json
Follows https://github.com/symfony/symfony/pull/46115
=> [routing] Remove useless config in routes.yaml

symfony/messenger/6.0/config/packages/messenger.yaml
Add hint for test config
| Doc issue/PR  | [symfony/symfony-docs#...](https://symfony.com/doc/current/messenger.html#in-memory-transport)
=> [Messenger] Add hint test config

symfony/security-bundle/6.0/config/packages/security.yaml, symfony/security-bundle/6.0/manifest.json
| Doc issue/PR  | symfony/symfony#44554
=> Remove enable_authenticator_manager from symfony 6 recipe

symfony/web-profiler-bundle/6.1/config/packages/web_profiler.yaml, symfony/web-profiler-bundle/6.1/config/routes/web_profiler.yaml, symfony/web-profiler-bundle/6.1/manifest.json
See https://github.com/symfony/symfony/pull/46625 for background.
=> [web-profiler-bundle] Enable serializer data collector on 6.1

symfony/ux-live-component/2.0/config/routes/ux_live_component.yaml, symfony/ux-live-component/2.0/manifest.json
| Doc issue/PR  | https://github.com/symfony/ux/pull/336
Finally adding the live component recipe, which just involves adding a route import.
Cheers!
=> Adding ux-live-component recipe

symfony/sms-factor-notifier/6.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/16901
=> [Notifier] Add SMSFactor bridge recipe

symfony/framework-bundle/6.2/config/packages/cache.yaml, symfony/framework-bundle/6.2/config/packages/framework.yaml, symfony/framework-bundle/6.2/config/preload.php, symfony/framework-bundle/6.2/config/routes/framework.yaml, symfony/framework-bundle/6.2/config/services.yaml, symfony/framework-bundle/6.2/manifest.json, symfony/framework-bundle/6.2/post-install.txt, symfony/framework-bundle/6.2/public/index.php, symfony/framework-bundle/6.2/src/Kernel.php
Blocked by https://github.com/symfony/symfony/pull/45997
=> [FramworkBundle] Added config framework.catch_all_throwables: true

symfony/all-my-sms-notifier/5.3/manifest.json, symfony/gateway-api-notifier/5.3/manifest.json, symfony/mailjet-notifier/5.4/manifest.json, symfony/orange-sms-notifier/6.1/manifest.json, symfony/vonage-notifier/5.4/manifest.json
=> Fix broken & missing notifier recipes

symfony/flex/1.0/.env
| Doc issue/PR  | Take over https://github.com/symfony/recipes/pull/979
cf https://github.com/symfony/recipes/pull/979#discussion_r711774071
=> Link best practice doc part to secret management

symfony/mail-pace-mailer/6.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/16896
=> Add symfony/mail-pace-mailer recipe

doctrine/doctrine-bundle/1.12/manifest.json, doctrine/doctrine-bundle/1.6/manifest.json, doctrine/doctrine-bundle/2.0/manifest.json, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.4/manifest.json
* Upgrade the recipe to add a Postgres 14 image
* Update the DSN for consistency and to reference the latest versions of the DBMS
* Make the user/db/password consistent with API Platform and Mercure
=> [doctrine-bundle] Upgrade to Postgres 14 and MySQL 8

symfony/chatwork-notifier/6.2/manifest.json
| Doc issue/PR  | symfony/symfony-docs#17230
DNS recipe for new Chatwork Notifier: https://github.com/symfony/symfony/pull/47373
=> Add chatwork notifier

api-platform/core/3.0/config/routes/api_platform.yaml, api-platform/core/3.0/manifest.json, api-platform/core/3.0/post-install.txt
Preparing v3 release see https://github.com/api-platform/api-platform/pull/2249
ping @dunglas
=> [api-platform/core] add 3.0 default configuration

symfony/webpack-encore-bundle/1.10/package.json, symfony/webpack-encore-bundle/1.10/webpack.config.js
Related to https://github.com/symfony/webpack-encore/pull/1142, ping @weaverryan
=> symfony/webpack-encore: bump to ^4.0.0, add peer dependencies webpack, webpack-cli, @babel/core and @babel/preset-env

league/oauth2-server-bundle/0.4/config/packages/league_oauth2_server.yaml, league/oauth2-server-bundle/0.4/config/routes/league_oauth2_server.yaml, league/oauth2-server-bundle/0.4/manifest.json, league/oauth2-server-bundle/0.4/post-install.txt
This bundle is maintained by myself and is an alternative to the no-longer-maintained FOSOAuthServerBundle.
=> [league/oauth2-server-bundle] Add the recipe

symfony/framework-bundle/6.2/config/packages/framework.yaml
Sidekick of https://github.com/symfony/symfony/pull/47467
=> Rename to handle_all_throwables

symfony/free-mobile-notifier/5.1/manifest.json
|Q | A|
|-- | --|
License | MIT
Doc issue/PR | -
=> [Notifier] Update FreeMobile DSN

league/oauth2-server-bundle/0.4/manifest.json
=> [league/oauth2-server-bundle] Ignore generated public and private keys

symfony/routing/6.2/config/packages/routing.yaml, symfony/routing/6.2/config/routes.yaml, symfony/routing/6.2/manifest.json
| Doc issue/PR  | TODO
Leverage symfony/symfony#47916
=> Leverage PSR-4 routing

symfony/routing/6.2/config/routes.yaml
See https://github.com/symfony/symfony/pull/47943
=> Fix syntax for the PSR4 routing loader

doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.0/post-install.txt, doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.3/post-install.txt, doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.4/post-install.txt
=> Use PostgreSQL 14 everywhere

.github/versions.json, symfony/isendpro-notifier/6.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#17450
Add the recipe for the new iSendPro notifier. Related with the PR : https://github.com/symfony/symfony/pull/48253
=> [Notifier] Add iSendPro bridge

.github/versions.json, symfony/termii-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17486
=> [Notifier] Add Termii bridge

.github/versions.json, symfony/ring-central-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17485
=> [Notifier] Add RingCentral bridge

.github/versions.json, symfony/plivo-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17484
=> [Notifier] Add Plivo bridge

symfony/twitter-notifier/6.3/manifest.json
https://github.com/symfony/symfony/pull/48084
=> [Notifier] Add Twitter bridge

symfony/mastodon-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17411
Related to PR https://github.com/symfony/symfony/pull/48101
=> [Notifier] Add Mastodon Notifier recipe

symfony/webpack-encore-bundle/1.10/config/packages/webpack_encore.yaml
=> Fixing typo `3rg` and minor rewording

php-cs-fixer/shim/3.0/.php-cs-fixer.dist.php, php-cs-fixer/shim/3.0/manifest.json
Add recipe for php-cs-fixer/shim.
=> Add recipe for php-cs-fixer/shim

doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.12/manifest.json, doctrine/doctrine-bundle/1.12/post-install.txt, doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.6/manifest.json, doctrine/doctrine-bundle/1.6/post-install.txt, doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.0/manifest.json, doctrine/doctrine-bundle/2.0/post-install.txt, doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.3/post-install.txt, doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.4/manifest.json, doctrine/doctrine-bundle/2.4/post-install.txt, doctrine/doctrine-bundle/2.8/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.8/manifest.json, doctrine/doctrine-bundle/2.8/post-install.txt
=> Use PostgreSQL 15 by default

symfony/pager-duty-notifier/6.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#17738
=> [Notifier] Add PagerDuty bridge

symfony/mercure-bundle/0.3/manifest.json
| Doc issue/PR  | https://github.com/dunglas/mercure/pull/739
=> [Mercure] remove -config by --config

doctrine/doctrine-bundle/1.12/manifest.json, doctrine/doctrine-bundle/1.6/manifest.json, doctrine/doctrine-bundle/2.0/manifest.json, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.4/manifest.json
Consistency with the service name.
=> [doctrine-bundle] make Docker volume name consistent

symfony/messenger/6.0/manifest.json, symfony/messenger/6.0/post-install.txt, symfony/webapp-pack/1.0/manifest.json
=> Remove `MESSENGER_TRANSPORT_DSN` from `webapp-pack` and enable one in messenger

symfony/webhook/6.3/config/routes/webhook.yaml, symfony/webhook/6.3/manifest.json
=> Add webhook recipe

zenstruck/messenger-test/1.7/manifest.json, zenstruck/messenger-test/1.7/post-install.txt
I think this package is well-used enough to justify the recipe here.
=> [zenstruck/messenger-test] add recipe

symfony/smsmode-notifier/6.3/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/17511
=> [Notifier] Add Smsmode bridge

symfony/pushover-notifier/6.3/manifest.json
| Doc issue/PR  | symfony/symfony-docs#17928
=> [Notifier] Add Pushover bridge

symfony/novu-notifier/6.4/manifest.json
| Doc issue/PR  | symfony/symfony#50414
=> [Notifier] Add Novu bridge

symfony/ntfy-notifier/6.4/manifest.json
| PR            | https://github.com/symfony/symfony/pull/50131
Add [Ntfy](https://ntfy.sh/) notifier bridge
=> [Notifier] add Ntfy notifier

symfony/panther/1.0/manifest.json
=> [symfony/panther] Set warn_if_missing=true when trying to add lines to phpunit.xml.dist

symfony/mailersend-mailer/6.3/manifest.json
| Doc PR  | https://github.com/symfony/symfony-docs/pull/17926
| Symfony PR  | https://github.com/symfony/symfony/pull/49461
=> Add symfony/mailersend-mailer recipe

symfony/redlink-notifier/manifest.json
| Doc issue/PR  | [symfony/symfony-docs#18263](https://github.com/symfony/symfony-docs/pull/18263)
Added redlink notifier.
=> [Notifier] Added redlink notifier

phpunit/phpunit/4.7/phpunit.xml.dist, phpunit/phpunit/9.6/.env.test, phpunit/phpunit/9.6/manifest.json, phpunit/phpunit/9.6/phpunit.xml.dist, phpunit/phpunit/9.6/tests/bootstrap.php, symfony/phpunit-bridge/5.1/phpunit.xml.dist, symfony/phpunit-bridge/5.3/phpunit.xml.dist, symfony/phpunit-bridge/6.3/.env.test, symfony/phpunit-bridge/6.3/bin/phpunit, symfony/phpunit-bridge/6.3/manifest.json, symfony/phpunit-bridge/6.3/phpunit.xml.dist, symfony/phpunit-bridge/6.3/post-install.txt, symfony/phpunit-bridge/6.3/tests/bootstrap.php
See https://github.com/sebastianbergmann/phpunit/pull/5419 for background.
=> Comment <extensions> tag before PHPUnit 9.6

symfony/brevo-notifier/6.4/manifest.json
| Doc issue/PR  | symfony/symfony-docs#18544
=> Add symfony/brevo-notifier recipe

symfony/brevo-mailer/6.4/manifest.json
| Doc issue/PR  | [symfony/symfony/pull/50302](https://github.com/symfony/symfony/pull/50302)
=> Add symfony/brevo-mailer recipe

symfony/framework-bundle/6.4/config/packages/cache.yaml, symfony/framework-bundle/6.4/config/packages/framework.yaml, symfony/framework-bundle/6.4/config/preload.php, symfony/framework-bundle/6.4/config/routes/framework.yaml, symfony/framework-bundle/6.4/config/services.yaml, symfony/framework-bundle/6.4/manifest.json, symfony/framework-bundle/6.4/post-install.txt, symfony/framework-bundle/6.4/public/index.php, symfony/framework-bundle/6.4/src/Kernel.php, symfony/framework-bundle/7.0/config/packages/cache.yaml, symfony/framework-bundle/7.0/config/packages/framework.yaml, symfony/framework-bundle/7.0/config/preload.php, symfony/framework-bundle/7.0/config/routes/framework.yaml, symfony/framework-bundle/7.0/config/services.yaml, symfony/framework-bundle/7.0/manifest.json, symfony/framework-bundle/7.0/post-install.txt, symfony/framework-bundle/7.0/public/index.php, symfony/framework-bundle/7.0/src/Kernel.php
| Doc issue/PR  | symfony/symfony#50888
=> Disable doctrine/annotations integration

symfony/goip-notifier/6.4/manifest.json
| Doc issue/PR  | symfony/symfony#51349
Add GoIP notifier bridge
=> [Notifier] Add GoIP bridge

api-platform/core/3.2/config/packages/api_platform.yaml
Fixes an issue introduced in #1240.
=> [api-platform/core] fix config

symfony/asset-mapper/6.4/importmap.php
minor spacing inconsistency fix
=> asset-mapper: fix minor whitespace inconsistency in importmap.php

symfony/azure-mailer/7.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony/pull/52842
=> Add Azure mailer

symfony/smsbox-notifier/7.1/manifest.json
| Doc issue/PR  | symfony/symfony-docs#19315
=> [Notifier] Add Smsbox notifier bridge

symfony/sevenio-notifier/7.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony/pull/52936
=> Add `symfony/sevenio-notifier`

symfony/asset-mapper/6.4/assets/app.js
| Doc issue/PR  | None
Not strictly necessary, but I think we're better including them.
=> [AssetMapper] Use semicolons in JavaScript

symfony/resend-mailer/7.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/19432
Related to https://github.com/symfony/symfony/pull/53554
=> [Mailer] Add Resend bridge recipe

doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.12/manifest.json, doctrine/doctrine-bundle/1.12/post-install.txt, doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml, doctrine/doctrine-bundle/1.6/manifest.json, doctrine/doctrine-bundle/1.6/post-install.txt, doctrine/doctrine-bundle/2.0/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.0/manifest.json, doctrine/doctrine-bundle/2.0/post-install.txt, doctrine/doctrine-bundle/2.10/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.10/manifest.json, doctrine/doctrine-bundle/2.10/post-install.txt, doctrine/doctrine-bundle/2.3/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.3/manifest.json, doctrine/doctrine-bundle/2.3/post-install.txt, doctrine/doctrine-bundle/2.4/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.4/manifest.json, doctrine/doctrine-bundle/2.4/post-install.txt, doctrine/doctrine-bundle/2.8/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.8/manifest.json, doctrine/doctrine-bundle/2.8/post-install.txt, doctrine/doctrine-bundle/2.9/config/packages/doctrine.yaml, doctrine/doctrine-bundle/2.9/manifest.json, doctrine/doctrine-bundle/2.9/post-install.txt
=> Bump to PostgreSQL 16

symfony/pushy-notifier/7.1/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/19555
Code: https://github.com/symfony/symfony/pull/53927
=> [Notifier][Pushy] Add recipe for Pushy notifier

symfony/primotexto-notifier/7.1/manifest.json
| Doc issue/PR  | [symfony/symfony-docs#19835](https://github.com/symfony/symfony-docs/pull/19835)
Code : [symfony/symfony#54747](https://github.com/symfony/symfony/pull/54747)
=> [Notifier] [Primotexto] Add recipe for Primotexto notifier

symfony/ux-lazy-image/2.17/config/packages/lazy_image.yaml, symfony/ux-lazy-image/2.17/manifest.json, symfony/ux-lazy-image/2.18/config/packages/lazy_image.yaml, symfony/ux-lazy-image/2.18/manifest.json
Hi everyone, this PR adds the recipe for `symfony/ux-lazy-image`. 
It does not configure anything, instead it gives some hints about the bundle possibilities :)
=> [UX LazyImage] Add initial recipe

symfony/mailomat-mailer/7.2/manifest.json
| Doc PR  | https://github.com/symfony/symfony-docs/pull/19978
| Feature PR | https://github.com/symfony/symfony/pull/57456
=> [Mailer] Add mailomat mailer recipe

symfony/sipgate-notifier/7.2/manifest.json
| Doc issue/PR  | [symfony/symfony-docs#...](https://github.com/symfony/symfony/pull/57627)
=> [Notifier] Add Sipgate

symfony/postal-mailer/7.2/manifest.json
| Doc issue/PR  | symfony/symfony-docs#20088
=> add Postal mailer

symfony/joli-notif-notifier/7.2/manifest.json
| Doc issue/PR  | symfony/symfony#57683
=> [Notifier] Add recipe for `JoliNotif` bridge

symfony/mailtrap-mailer/7.2/manifest.json
| Doc issue/PR  | https://github.com/symfony/symfony-docs/pull/20217
Recipe for
* https://github.com/symfony/symfony/pull/58252.
=> [Mailer] add Mailtrap bridge

symfony/form/7.2/config/packages/csrf.yaml, symfony/form/7.2/manifest.json, symfony/framework-bundle/7.2/config/packages/framework.yaml
As suggested in https://github.com/symfony/symfony/pull/58937#discussion_r1850167844
=> Move stateless CSRF config to packages/csrf.yaml

symfony/flex/2.4/.env, symfony/flex/2.4/manifest.json
Otherwise flex cannot populate it with APP_SECRET
=> [flex/2.4] Add missing .env.dev file

.github/workflows/callable-qa.yml
=> Update the callable-qa workflow to avoid GHA deprecations

symfony/ux-live-component/2.6/manifest.json
Would help DX during install of most used UX packages
=> [LiveComponent] Add alias "live-component"

symfony/ux-twig-component/2.13/manifest.json
Would help DX during install of most used UX packages
=> [TwigComponent] Add alias "twig-component"

symfony/framework-bundle/6.4/.editorconfig, symfony/framework-bundle/6.4/manifest.json, symfony/framework-bundle/7.2/.editorconfig, symfony/framework-bundle/7.2/manifest.json, symfony/framework-bundle/7.3/.editorconfig, symfony/framework-bundle/7.3/manifest.json
Maybe too _meta_ for the recipe but this is something I add to every project for consistency.
=> [symfony/framework-bundle] add `.editorconfig`

README.rst
=> Update README to tell about all configurators

symfony/panther/1.0/manifest.json
=> [symfony/panther] Fix legacy ENV definition

symfony/web-profiler-bundle/7.3/config/packages/web_profiler.yaml
=> enable `framework.profiler.collect_serializer_data` in the `test` environment

symfony/routing/7.4/config/packages/routing.yaml, symfony/routing/7.4/manifest.json
https://github.com/symfony/recipes/pull/1416 missed updating for 7.4
/cc @alexander-schranz FYI in case you want to tweak this another day
=> [routing] sync DEFAULT_URI from 7.0
